export interface Product {
  id: number;
  categoryId: string;
  name: string;
  name_tr: string;
  name_en: string;
  description?: string;
  description_tr?: string;
  description_en?: string;
  technicalCode: string;
  material: string;
  certification: string;
  price: number;
  quantity: number;
  inStock: boolean;
  specs: Record<string, string>;
  specs_tr?: Record<string, string>;
  specs_en?: Record<string, string>;
  datasheet?: string;
  image?: string;
}

export interface Category {
  id: string;
  name: string;
  name_tr: string;
  name_en: string;
  slug: string;
  description: string;
  description_tr: string;
  description_en: string;
  icon: string;
}

export const categories: Category[] = [
  {
    id: "ndt",
    name: "NDT Sarfları",
    name_tr: "NDT Sarfları",
    name_en: "NDT Supplies",
    slug: "ndt",
    description: "Tahribatsız muayene malzemeleri ve test ekipmanları",
    description_tr: "Tahribatsız muayene malzemeleri ve test ekipmanları",
    description_en: "Non-destructive testing materials and inspection equipment",
    icon: "AlertCircle"
  },
  {
    id: "welding",
    name: "Kaynak & Alaşım",
    name_tr: "Kaynak & Alaşım",
    name_en: "Welding & Alloys",
    slug: "welding",
    description: "Özel kaynak telleri ve alaşım ürünleri",
    description_tr: "Özel kaynak telleri ve alaşım ürünleri",
    description_en: "Specialized welding wires and alloy products",
    icon: "Zap"
  },
  {
    id: "construction",
    name: "Yapı Kimyasalları",
    name_tr: "Yapı Kimyasalları",
    name_en: "Construction Chemicals",
    slug: "construction",
    description: "İleri yapı kimyasalları ve sabitleyiciler",
    description_tr: "İleri yapı kimyasalları ve sabitleyiciler",
    description_en: "Advanced construction chemicals and fasteners",
    icon: "Beaker"
  },
  {
    id: "surface",
    name: "Yüzey İşlem",
    name_tr: "Yüzey İşlem",
    name_en: "Surface Treatment",
    slug: "surface",
    description: "Yüzey işlem ve aşındırıcı ürünleri",
    description_tr: "Yüzey işlem ve aşındırıcı ürünleri",
    description_en: "Surface treatment and abrasive products",
    icon: "Wrench"
  },
  {
    id: "safety",
    name: "İş Güvenliği",
    name_tr: "İş Güvenliği",
    name_en: "Safety Equipment",
    slug: "safety",
    description: "Nitelikli iş güvenliği ekipmanları",
    description_tr: "Nitelikli iş güvenliği ekipmanları",
    description_en: "Qualified occupational safety equipment",
    icon: "Shield"
  }
];

export function getProductById(id: number): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter(p => p.categoryId === categoryId);
}

export const products: Product[] = [
  // NDT Supplies (1-10)
  { id: 1, categoryId: "ndt", name: "Penetrant Test Spreyi - Kırmızı", name_tr: "Penetrant Test Spreyi - Kırmızı", name_en: "Penetrant Test Spray - Red", description_tr: "Yüksek görünürlüklü kırmızı penetrant test sıvısı", description_en: "High-visibility red penetrant test liquid", technicalCode: "PT-500-RED", material: "Kimyasal Penetrant", certification: "ISO 3104", price: 250, quantity: 150, inStock: true, specs: { viskozite: "10-15 cSt", parlamaNoktas: ">100°C", yogunluk: "0.85 g/cm3", renk: "Kırmızı" }, specs_tr: { viskozite: "10-15 cSt", parlamaNoktas: ">100°C", yogunluk: "0.85 g/cm3", renk: "Kırmızı" }, specs_en: { viscosity: "10-15 cSt", flashPoint: ">100°C", density: "0.85 g/cm3", color: "Red" }, datasheet: 'https://example.com/datasheets/PT-500.pdf', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop' },
  { id: 2, categoryId: "ndt", name: "Manyetik Parçacık Tozu - Siyah", name_tr: "Manyetik Parçacık Tozu - Siyah", name_en: "Magnetic Particle Powder - Black", description_tr: "Manyetik parçacık muayenesi için ferromanyetik toz", description_en: "Ferromagnetic powder for magnetic particle inspection", technicalCode: "MPT-100-RED", material: "Demir Oksit", certification: "ASTM E1316", price: 180, quantity: 200, inStock: true, specs: { parcacik: "1-10 um", yogunluk: "2.8 g/cm3", renk: "Siyah" }, specs_tr: { parcacik: "1-10 um", yogunluk: "2.8 g/cm3", renk: "Siyah" }, specs_en: { particle: "1-10 um", density: "2.8 g/cm3", color: "Black" }, datasheet: 'https://example.com/datasheets/MagParticle-100.pdf', image: 'https://images.unsplash.com/photo-1530311701074-9ef4a446f62b?q=80&w=800&auto=format&fit=crop' },
  { id: 3, categoryId: "ndt", name: "UT Jeli - Standart", name_tr: "UT Jeli - Standart", name_en: "Ultrasonic Gel - Standard", description_tr: "Ultrasonik muayene için akustik bağlantı jeli", description_en: "Acoustic coupling gel for ultrasonic testing", technicalCode: "UTJ-1L", material: "Polimer Jel", certification: "ISO 2409", price: 95, quantity: 300, inStock: true, specs: { viskozite: "Yüksek", iletkenlik: "İyi", sicaklik: "-10 ile +50°C" }, specs_tr: { viskozite: "Yüksek", iletkenlik: "İyi", sicaklik: "-10 ile +50°C" }, specs_en: { viscosity: "High", conductivity: "Good", temperature: "-10 to +50°C" }, datasheet: 'https://example.com/datasheets/UTGel-500.pdf', image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=800&auto=format&fit=crop' },
  { id: 4, categoryId: "ndt", name: "UT Jeli - Yüksek Sıcaklık", name_tr: "UT Jeli - Yüksek Sıcaklık", name_en: "Ultrasonic Gel - High Temperature", description_tr: "Yüksek sıcaklık ultrasonik muayene jeli", description_en: "High-temperature ultrasonic testing gel", technicalCode: "UTJ-HT", material: "Polimer Jel", certification: "ISO 2409", price: 145, quantity: 100, inStock: true, specs: { viskozite: "Yüksek", iletkenlik: "Mükemmel", sicaklik: "-20 ile +80°C" }, specs_tr: { viskozite: "Yüksek", iletkenlik: "Mükemmel", sicaklik: "-20 ile +80°C" }, specs_en: { viscosity: "High", conductivity: "Excellent", temperature: "-20 to +80°C" }, datasheet: 'https://example.com/datasheets/UTGel-HT.pdf', image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800&auto=format&fit=crop' },
  { id: 5, categoryId: "ndt", name: "Temizleme Spreyi - Penetrant Kalıntı", name_tr: "Temizleme Spreyi - Penetrant Kalıntı", name_en: "Cleaning Spray - Penetrant Residue", description_tr: "Penetrant kalıntı temizliği için organik çözücü", description_en: "Organic solvent for penetrant residue removal", technicalCode: "CLS-500", material: "Organik Çözücü", certification: "ISO 3104", price: 120, quantity: 250, inStock: true, specs: { buharlas: "Hızlı", kalintilar: "Minimum", kokusuz: "Evet" }, specs_tr: { buharlas: "Hızlı", kalintilar: "Minimum", kokusuz: "Evet" }, specs_en: { evaporation: "Fast", residue: "Minimum", odorless: "Yes" }, datasheet: 'https://example.com/datasheets/CLS-500.pdf', image: 'https://images.unsplash.com/photo-1584017945516-793540199e6f?q=80&w=800&auto=format&fit=crop' },
  { id: 6, categoryId: "ndt", name: "Geliştirici Toz - Beyaz", name_tr: "Geliştirici Toz - Beyaz", name_en: "Developer Powder - White", description_tr: "Penetrant muayenesi için titanyum dioksit geliştirici", description_en: "Titanium dioxide developer for penetrant testing", technicalCode: "DEV-WH", material: "Titanyum Dioksit", certification: "ASTM E1417", price: 210, quantity: 80, inStock: true, specs: { parcacik: "5-50 um", yogunluk: "3.9 g/cm3", renk: "Beyaz" }, specs_tr: { parcacik: "5-50 um", yogunluk: "3.9 g/cm3", renk: "Beyaz" }, specs_en: { particle: "5-50 um", density: "3.9 g/cm3", color: "White" }, datasheet: 'https://example.com/datasheets/DEV-WH.pdf', image: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?q=80&w=800&auto=format&fit=crop' },
  { id: 7, categoryId: "ndt", name: "Kalibrasyonu Kontrol Bloğu", name_tr: "Kalibrasyonu Kontrol Bloğu", name_en: "Calibration Control Block", description_tr: "Sertlik muayenesi için çelik kalibrasyonu standardı", description_en: "Steel calibration standard for hardness testing", technicalCode: "CAL-STD", material: "Çelik", certification: "ISO 6506", price: 450, quantity: 30, inStock: true, specs: { boyut: "50x50x50 mm", sertlik: "58-62 HRC", hassasiyet: "+/-0.01 mm" }, specs_tr: { boyut: "50x50x50 mm", sertlik: "58-62 HRC", hassasiyet: "+/-0.01 mm" }, specs_en: { size: "50x50x50 mm", hardness: "58-62 HRC", accuracy: "+/-0.01 mm" }, datasheet: 'https://example.com/datasheets/CAL-STD.pdf', image: 'https://images.unsplash.com/photo-1535813543266-73f83195c3e4?q=80&w=800&auto=format&fit=crop' },
  { id: 8, categoryId: "ndt", name: "Floresans Penetrant Spreyi", name_tr: "Floresans Penetrant Spreyi", name_en: "Fluorescent Penetrant Spray", description_tr: "UV muayenesi için yüksek görünürlüklü floresans penetrant", description_en: "High-visibility fluorescent penetrant for UV inspection", technicalCode: "FPT-500", material: "Floresans Penetrant", certification: "ISO 3104", price: 320, quantity: 60, inStock: true, specs: { parlaklik: "Yüksek", dalga: "365 nm", suresi: "8-10 saat" }, specs_tr: { parlaklik: "Yüksek", dalga: "365 nm", suresi: "8-10 saat" }, specs_en: { brightness: "High", wavelength: "365 nm", duration: "8-10 hours" }, datasheet: 'https://example.com/datasheets/FPT-500.pdf', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop' },
  { id: 9, categoryId: "ndt", name: "Radyografik Film - Tip D", name_tr: "Radyografik Film - Tip D", name_en: "Radiographic Film - Type D", description_tr: "X-ray muayenesi için endüstriyel radyografik film", description_en: "Industrial radiographic film for X-ray testing", technicalCode: "RAD-D", material: "Fotoğrafik Film", certification: "ISO 11699", price: 280, quantity: 100, inStock: true, specs: { hassasiyet: "Orta", kontrast: "Yüksek", boyut: "100x150 mm" }, specs_tr: { hassasiyet: "Orta", kontrast: "Yüksek", boyut: "100x150 mm" }, specs_en: { sensitivity: "Medium", contrast: "High", size: "100x150 mm" }, datasheet: 'https://example.com/datasheets/RAD-D.pdf', image: 'https://images.unsplash.com/photo-1530210124550-912dc1381cb8?q=80&w=800&auto=format&fit=crop' },
  { id: 10, categoryId: "ndt", name: "Eddy Current Prob - 5mm", name_tr: "Eddy Current Prob - 5mm", name_en: "Eddy Current Probe - 5mm", description_tr: "Yüzey muayenesi için hassas eddy current probu", description_en: "Precision eddy current probe for surface inspection", technicalCode: "ECP-5", material: "Bakır Alaşımı", certification: "ISO 15549", price: 380, quantity: 40, inStock: true, specs: { cap: "5 mm", frekans: "100 kHz", hassasiyet: "Yüksek" }, specs_tr: { cap: "5 mm", frekans: "100 kHz", hassasiyet: "Yüksek" }, specs_en: { diameter: "5 mm", frequency: "100 kHz", sensitivity: "High" }, datasheet: 'https://example.com/datasheets/ECP-5.pdf', image: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?q=80&w=800&auto=format&fit=crop' },

  // Welding & Alloys (11-20)
  { id: 11, categoryId: "welding", name: "IN718 Uyumlu TIG Teli - 1.6mm", name_tr: "IN718 Uyumlu TIG Teli - 1.6mm", name_en: "IN718 Compatible TIG Wire - 1.6mm", description_tr: "Yüksek sıcaklık uygulamaları için nikel alaşımı TIG kaynak teli", description_en: "Nickel alloy TIG welding wire for high-temperature applications", technicalCode: "ER308L-1.6", material: "Nikel Alaşımı", certification: "AWS A5.14", price: 450, quantity: 500, inStock: true, specs: { cap: "1.6 mm", cekme: "480 MPa", akma: "170 MPa", uzama: "%35" }, specs_tr: { cap: "1.6 mm", cekme: "480 MPa", akma: "170 MPa", uzama: "%35" }, specs_en: { diameter: "1.6 mm", tensile: "480 MPa", yield: "170 MPa", elongation: "%35" }, datasheet: 'https://example.com/datasheets/ER308L-1.6.pdf', image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop' },
  { id: 12, categoryId: "welding", name: "IN718 Uyumlu TIG Teli - 2.4mm", name_tr: "IN718 Uyumlu TIG Teli - 2.4mm", name_en: "IN718 Compatible TIG Wire - 2.4mm", description_tr: "Yüksek sıcaklık uygulamaları için nikel alaşımı TIG kaynak teli", description_en: "Nickel alloy TIG welding wire for high-temperature applications", technicalCode: "ER308L-2.4", material: "Nikel Alaşımı", certification: "AWS A5.14", price: 480, quantity: 350, inStock: true, specs: { cap: "2.4 mm", cekme: "480 MPa", akma: "170 MPa", uzama: "%35" }, specs_tr: { cap: "2.4 mm", cekme: "480 MPa", akma: "170 MPa", uzama: "%35" }, specs_en: { diameter: "2.4 mm", tensile: "480 MPa", yield: "170 MPa", elongation: "%35" }, datasheet: 'https://example.com/datasheets/ER308L-2.4.pdf', image: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop' },
  { id: 13, categoryId: "welding", name: "Gümüş Kaynak Pastası - %45", name_tr: "Gümüş Kaynak Pastası - %45", name_en: "Silver Brazing Paste - %45", description_tr: "Metal birleştirme için yüksek dayanımlı gümüş kaynak pastası", description_en: "High-strength silver brazing paste for metal joining", technicalCode: "AG-45", material: "Gümüş %45", certification: "DIN 1707", price: 520, quantity: 150, inStock: true, specs: { erimeSicakligi: "780°C", dayanim: "250 MPa", akiskanlik: "İyi" }, specs_tr: { erimeSicakligi: "780°C", dayanim: "250 MPa", akiskanlik: "İyi" }, specs_en: { meltingPoint: "780°C", strength: "250 MPa", fluidity: "Good" }, datasheet: 'https://example.com/datasheets/AG-45.pdf', image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop' },
  { id: 14, categoryId: "welding", name: "Gümüş Kaynak Pastası - %56", name_tr: "Gümüş Kaynak Pastası - %56", name_en: "Silver Brazing Paste - %56", description_tr: "Yüksek dayanımlı gümüş kaynak pastası", description_en: "High-strength silver brazing paste", technicalCode: "AG-56", material: "Gümüş %56", certification: "DIN 1707", price: 680, quantity: 100, inStock: true, specs: { erimeSicakligi: "650°C", dayanim: "300 MPa", akiskanlik: "Mükemmel" }, specs_tr: { erimeSicakligi: "650°C", dayanim: "300 MPa", akiskanlik: "Mükemmel" }, specs_en: { meltingPoint: "650°C", strength: "300 MPa", fluidity: "Excellent" }, datasheet: 'https://example.com/datasheets/AG-56.pdf', image: 'https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop' },
  { id: 15, categoryId: "welding", name: "Alüminyum Kaynak Teli - 4043", name_tr: "Alüminyum Kaynak Teli - 4043", name_en: "Aluminum Welding Wire - 4043", description_tr: "Genel amaçlı alüminyum alaşımı kaynak teli", description_en: "General-purpose aluminum alloy welding wire", technicalCode: "AL-4043", material: "Alüminyum", certification: "AWS A5.10", price: 280, quantity: 400, inStock: true, specs: { cap: "1.2 mm", erimeSicakligi: "630°C", dayanim: "165 MPa" }, specs_tr: { cap: "1.2 mm", erimeSicakligi: "630°C", dayanim: "165 MPa" }, specs_en: { diameter: "1.2 mm", meltingPoint: "630°C", strength: "165 MPa" }, datasheet: 'https://example.com/datasheets/AL-4043.pdf', image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop' },
  { id: 16, categoryId: "welding", name: "Alüminyum Kaynak Teli - 5356", name_tr: "Alüminyum Kaynak Teli - 5356", name_en: "Aluminum Welding Wire - 5356", description_tr: "Denizcilik uygulamaları için alüminyum alaşımı kaynak teli", description_en: "Aluminum alloy welding wire for marine applications", technicalCode: "AL-5356", material: "Alüminyum", certification: "AWS A5.10", price: 320, quantity: 300, inStock: true, specs: { cap: "1.6 mm", erimeSicakligi: "600°C", dayanim: "215 MPa" }, specs_tr: { cap: "1.6 mm", erimeSicakligi: "600°C", dayanim: "215 MPa" }, specs_en: { diameter: "1.6 mm", meltingPoint: "600°C", strength: "215 MPa" }, datasheet: 'https://example.com/datasheets/AL-5356.pdf', image: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop' },
  { id: 17, categoryId: "welding", name: "Titanyum Kaynak Teli - Derece 5", name_tr: "Titanyum Kaynak Teli - Derece 5", name_en: "Titanium Welding Wire - Grade 5", description_tr: "Havacılık uygulamaları için titanyum alaşımı kaynak teli", description_en: "Titanium alloy welding wire for aerospace applications", technicalCode: "TI-GR5", material: "Titanyum", certification: "AWS A5.16", price: 680, quantity: 150, inStock: true, specs: { cap: "1.2 mm", cekme: "880 MPa", akma: "760 MPa", uzama: "%14" }, specs_tr: { cap: "1.2 mm", cekme: "880 MPa", akma: "760 MPa", uzama: "%14" }, specs_en: { diameter: "1.2 mm", tensile: "880 MPa", yield: "760 MPa", elongation: "%14" }, datasheet: 'https://example.com/datasheets/TI-GR5.pdf', image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop' },
  { id: 18, categoryId: "welding", name: "Nikel Kaynak Teli - 200", name_tr: "Nikel Kaynak Teli - 200", name_en: "Nickel Welding Wire - 200", description_tr: "Korozyon direnci için saf nikel kaynak teli", description_en: "Pure nickel welding wire for corrosion resistance", technicalCode: "NI-200", material: "Nikel", certification: "AWS A5.14", price: 520, quantity: 200, inStock: true, specs: { cap: "1.6 mm", cekme: "380 MPa", akma: "150 MPa", uzama: "%40" }, specs_tr: { cap: "1.6 mm", cekme: "380 MPa", akma: "150 MPa", uzama: "%40" }, specs_en: { diameter: "1.6 mm", tensile: "380 MPa", yield: "150 MPa", elongation: "%40" }, datasheet: 'https://example.com/datasheets/NI-200.pdf', image: 'https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop' },
  { id: 19, categoryId: "welding", name: "Kobalt Kaynak Teli", name_tr: "Kobalt Kaynak Teli", name_en: "Cobalt Welding Rod", description_tr: "Yüksek sıcaklık kobalt kaynak teli", description_en: "High-temperature cobalt welding rod", technicalCode: "CO-WIRE", material: "Kobalt", certification: "AWS A5.21", price: 620, quantity: 120, inStock: true, specs: { cap: "2.4 mm", cekme: "600 MPa", akma: "400 MPa", sicaklik: "1000°C'ye kadar" }, specs_tr: { cap: "2.4 mm", cekme: "600 MPa", akma: "400 MPa", sicaklik: "1000°C'ye kadar" }, specs_en: { diameter: "2.4 mm", tensile: "600 MPa", yield: "400 MPa", temperature: "Up to 1000°C" }, datasheet: 'https://example.com/datasheets/CO-WIRE.pdf', image: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop' },
  { id: 20, categoryId: "welding", name: "Elektrot - E6013", name_tr: "Elektrot - E6013", name_en: "Electrode - E6013", description_tr: "Genel amaçlı çelik kaynak elektrod", description_en: "General-purpose steel welding electrode", technicalCode: "ELC-E6013", material: "Çelik", certification: "AWS A5.1", price: 180, quantity: 500, inStock: true, specs: { cap: "3.2 mm", dayanim: "430 MPa", akma: "345 MPa", uzama: "%22" }, specs_tr: { cap: "3.2 mm", dayanim: "430 MPa", akma: "345 MPa", uzama: "%22" }, specs_en: { diameter: "3.2 mm", strength: "430 MPa", yield: "345 MPa", elongation: "%22" }, datasheet: 'https://example.com/datasheets/E6013.pdf', image: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop' },

  // Construction Chemicals (21-30)
  { id: 21, categoryId: "construction", name: "Epoksi Akrilat Dübel - M12", name_tr: "Epoksi Akrilat Dübel - M12", name_en: "Epoxy Acrylic Anchor Dowel - M12", description_tr: "Beton için iki komponentli epoksi akrilat dübel", description_en: "Two-component epoxy acrylic anchor for concrete", technicalCode: "EA-M12", material: "Epoksi Reçine", certification: "ETA", price: 320, quantity: 200, inStock: true, specs: { cekme: "15 kN", kesme: "12 kN", kuruma: "30 dakika" }, specs_tr: { cekme: "15 kN", kesme: "12 kN", kuruma: "30 dakika" }, specs_en: { tension: "15 kN", shear: "12 kN", curing: "30 minutes" }, datasheet: 'https://example.com/datasheets/EA-M12.pdf', image: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?q=80&w=800&auto=format&fit=crop' },
  { id: 22, categoryId: "construction", name: "Epoksi Akrilat Dübel - M16", name_tr: "Epoksi Akrilat Dübel - M16", name_en: "Epoxy Acrylic Anchor Dowel - M16", description_tr: "Beton için iki komponentli epoksi akrilat dübel", description_en: "Two-component epoxy acrylic anchor for concrete", technicalCode: "EA-M16", material: "Epoksi Reçine", certification: "ETA", price: 380, quantity: 150, inStock: true, specs: { cekme: "25 kN", kesme: "20 kN", kuruma: "30 dakika" }, specs_tr: { cekme: "25 kN", kesme: "20 kN", kuruma: "30 dakika" }, specs_en: { tension: "25 kN", shear: "20 kN", curing: "30 minutes" }, datasheet: 'https://example.com/datasheets/EA-M16.pdf', image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop' },
  { id: 23, categoryId: "construction", name: "Poliüretan Mastik - 500ml", name_tr: "Poliüretan Mastik - 500ml", name_en: "Polyurethane Mastic - 500ml", description_tr: "Eklemler için esnek poliüretan sealant", description_en: "Flexible polyurethane sealant for joints", technicalCode: "PU-500", material: "Poliüretan", certification: "ISO 11600", price: 280, quantity: 300, inStock: true, specs: { elastiklik: "%25", dayaniklilik: "20 yil", renk: "Gri" }, specs_tr: { elastiklik: "%25", dayaniklilik: "20 yil", renk: "Gri" }, specs_en: { flexibility: "%25", durability: "20 years", color: "Grey" }, datasheet: 'https://example.com/datasheets/PU-500.pdf', image: 'https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop' },
  { id: 24, categoryId: "construction", name: "Poliüretan Mastik - 1L", name_tr: "Poliüretan Mastik - 1L", name_en: "Polyurethane Mastic - 1L", description_tr: "Eklemler için esnek poliüretan sealant", description_en: "Flexible polyurethane sealant for joints", technicalCode: "PU-1L", material: "Poliüretan", certification: "ISO 11600", price: 450, quantity: 200, inStock: true, specs: { elastiklik: "%25", dayaniklilik: "20 yil", renk: "Beyaz" }, specs_tr: { elastiklik: "%25", dayaniklilik: "20 yil", renk: "Beyaz" }, specs_en: { flexibility: "%25", durability: "20 years", color: "White" }, datasheet: 'https://example.com/datasheets/PU-1L.pdf', image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop' },
  { id: 25, categoryId: "construction", name: "Beton Tamir Harcı - 25kg", name_tr: "Beton Tamir Harcı - 25kg", name_en: "Concrete Repair Mortar - 25kg", description_tr: "Hızlı kurulama beton tamir harcı", description_en: "Fast-setting concrete repair mortar", technicalCode: "CRT-25", material: "Çimento Bazlı", certification: "EN 1504-3", price: 95, quantity: 500, inStock: true, specs: { dayanim: "30 MPa", kuruma: "24 saat", renk: "Gri" }, specs_tr: { dayanim: "30 MPa", kuruma: "24 saat", renk: "Gri" }, specs_en: { strength: "30 MPa", curing: "24 hours", color: "Grey" }, datasheet: 'https://example.com/datasheets/CRT-25.pdf', image: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?q=80&w=800&auto=format&fit=crop' },
  { id: 26, categoryId: "construction", name: "Beton Tamir Harcı - 50kg", name_tr: "Beton Tamir Harcı - 50kg", name_en: "Concrete Repair Mortar - 50kg", description_tr: "Hızlı kurulama beton tamir harcı", description_en: "Fast-setting concrete repair mortar", technicalCode: "CRT-50", material: "Çimento Bazlı", certification: "EN 1504-3", price: 160, quantity: 300, inStock: true, specs: { dayanim: "30 MPa", kuruma: "24 saat", renk: "Gri" }, specs_tr: { dayanim: "30 MPa", kuruma: "24 saat", renk: "Gri" }, specs_en: { strength: "30 MPa", curing: "24 hours", color: "Grey" }, datasheet: 'https://example.com/datasheets/CRT-50.pdf', image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop' },
  { id: 27, categoryId: "construction", name: "Silikon Sealant - Kartuş", name_tr: "Silikon Sealant - Kartuş", name_en: "Silicone Sealant - Cartridge", description_tr: "İnşaat için nötr kürlü silikon sealant", description_en: "Neutral-cure silicone sealant for construction", technicalCode: "SIL-300", material: "Silikon", certification: "ISO 11012", price: 85, quantity: 400, inStock: true, specs: { hacim: "300 ml", kuruma: "24 saat", esneklik: "Mükemmel" }, specs_tr: { hacim: "300 ml", kuruma: "24 saat", esneklik: "Mükemmel" }, specs_en: { volume: "300 ml", curing: "24 hours", flexibility: "Excellent" }, datasheet: 'https://example.com/datasheets/SIL-300.pdf', image: 'https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop' },
  { id: 28, categoryId: "construction", name: "Epoksi Reçine - 2 Komponentli", name_tr: "Epoksi Reçine - 2 Komponentli", name_en: "Epoxy Resin - 2K System", description_tr: "Yüksek dayanımlı yapıştırma için iki komponentli epoksi reçine", description_en: "Two-component epoxy resin for high-strength bonding", technicalCode: "EPS-2K", material: "Epoksi", certification: "ISO 2114", price: 380, quantity: 100, inStock: true, specs: { karisim: "1:1", kuruma: "24 saat", dayanim: "50 MPa" }, specs_tr: { karisim: "1:1", kuruma: "24 saat", dayanim: "50 MPa" }, specs_en: { ratio: "1:1", curing: "24 hours", strength: "50 MPa" }, datasheet: 'https://example.com/datasheets/EPS-2K.pdf', image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop' },
  { id: 29, categoryId: "construction", name: "Astar - Beton İçin", name_tr: "Astar - Beton İçin", name_en: "Primer - For Concrete", description_tr: "Beton için polimer bazlı astar", description_en: "Polymer-based primer for concrete", technicalCode: "PRM-CONC", material: "Polimer Bazlı", certification: "EN 1062-1", price: 220, quantity: 250, inStock: true, specs: { kapsama: "10 m2/L", kuruma: "4 saat", renk: "Beyaz" }, specs_tr: { kapsama: "10 m2/L", kuruma: "4 saat", renk: "Beyaz" }, specs_en: { coverage: "10 m2/L", drying: "4 hours", color: "White" }, datasheet: 'https://example.com/datasheets/PRM-CONC.pdf', image: 'https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?q=80&w=800&auto=format&fit=crop' },
  { id: 30, categoryId: "construction", name: "Yapıştırıcı - Yapı Taşı", name_tr: "Yapıştırıcı - Yapı Taşı", name_en: "Adhesive - Building Stone", description_tr: "Yapı taşı yapıştırması için polimer modifiye yapıştırıcı", description_en: "Polymer-modified adhesive for building stone", technicalCode: "ADH-STONE", material: "Polimer Modifiye", certification: "EN 12004", price: 180, quantity: 400, inStock: true, specs: { acikZaman: "15 dakika", dayanim: "1 MPa", renk: "Gri" }, specs_tr: { acikZaman: "15 dakika", dayanim: "1 MPa", renk: "Gri" }, specs_en: { openTime: "15 minutes", strength: "1 MPa", color: "Grey" }, datasheet: 'https://example.com/datasheets/ADH-STONE.pdf', image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop' },

  // Surface Treatment (31-40)
  { id: 31, categoryId: "surface", name: "Cam Küreciği Kumlama Kumu - 120 mesh", name_tr: "Cam Küreciği Kumlama Kumu - 120 mesh", name_en: "Glass Bead Blasting Media - 120 mesh", description_tr: "Hassas kumlama için cam küreleri", description_en: "Glass beads for precision blasting", technicalCode: "GK-120", material: "Cam", certification: "ISO 11126", price: 150, quantity: 400, inStock: true, specs: { granul: "120 mesh", sertlik: "5.5 Mohs", yogunluk: "2.5 g/cm3" }, specs_tr: { granul: "120 mesh", sertlik: "5.5 Mohs", yogunluk: "2.5 g/cm3" }, specs_en: { granule: "120 mesh", hardness: "5.5 Mohs", density: "2.5 g/cm3" }, datasheet: 'https://example.com/datasheets/GK-120.pdf', image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop' },
  { id: 32, categoryId: "surface", name: "Zirkonyum Flap Disk - 125mm", name_tr: "Zirkonyum Flap Disk - 125mm", name_en: "Zirconia Flap Disk - 125mm", description_tr: "Metal taşlama için zirkonyum flap disk", description_en: "Zirconia flap disk for metal grinding", technicalCode: "ZFD-125", material: "Zirkonyum", certification: "ISO 13696", price: 85, quantity: 600, inStock: true, specs: { cap: "125 mm", kum: "80", rpm: "12000" }, specs_tr: { cap: "125 mm", kum: "80", rpm: "12000" }, specs_en: { diameter: "125 mm", grit: "80", rpm: "12000" }, datasheet: 'https://example.com/datasheets/ZFD-125.pdf', image: 'https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop' },
  { id: 33, categoryId: "surface", name: "Silikon Karbid Taşlama Tekerleği", name_tr: "Silikon Karbid Taşlama Tekerleği", name_en: "Silicon Carbide Grinding Wheel", description_tr: "Hassas taşlama için silikon karbid tekerlek", description_en: "Silicon carbide wheel for precision grinding", technicalCode: "SCW-200", material: "Silikon Karbid", certification: "ISO 603", price: 220, quantity: 150, inStock: true, specs: { cap: "200 mm", kum: "120", sertlik: "Yüksek" }, specs_tr: { cap: "200 mm", kum: "120", sertlik: "Yüksek" }, specs_en: { diameter: "200 mm", grit: "120", hardness: "High" }, datasheet: 'https://example.com/datasheets/SCW-200.pdf', image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop' },
  { id: 34, categoryId: "surface", name: "Alüminyum Oksit Zımpara - 220 kum", name_tr: "Alüminyum Oksit Zımpara - 220 kum", name_en: "Aluminum Oxide Sandpaper - 220 grit", description_tr: "Ahşap işleme için alüminyum oksit zımpara", description_en: "Aluminum oxide sandpaper for wood finishing", technicalCode: "AOS-220", material: "Alüminyum Oksit", certification: "ISO 6344", price: 35, quantity: 1000, inStock: true, specs: { kum: "220", boyut: "230x280 mm", dayaniklilik: "Yüksek" }, specs_tr: { kum: "220", boyut: "230x280 mm", dayaniklilik: "Yüksek" }, specs_en: { grit: "220", size: "230x280 mm", durability: "High" }, datasheet: 'https://example.com/datasheets/AOS-220.pdf', image: 'https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop' },
  { id: 35, categoryId: "surface", name: "Emery Kumaş - 150 kum", name_tr: "Emery Kumaş - 150 kum", name_en: "Emery Cloth - 150 grit", description_tr: "Metal cilalama için emery kumaş", description_en: "Emery cloth for metal polishing", technicalCode: "EMC-150", material: "Emery", certification: "ISO 6344", price: 45, quantity: 800, inStock: true, specs: { kum: "150", genislik: "100 mm", dayaniklilik: "Mükemmel" }, specs_tr: { kum: "150", genislik: "100 mm", dayaniklilik: "Mükemmel" }, specs_en: { grit: "150", width: "100 mm", durability: "Excellent" }, datasheet: 'https://example.com/datasheets/EMC-150.pdf', image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop' },
  { id: 37, categoryId: "surface", name: "Cilalama Bileşimi - Metal", name_tr: "Cilalama Bileşimi - Metal", name_en: "Polishing Compound - Metal", description_tr: "Yüksek parlaklık için metal cilalama bileşimi", description_en: "Metal polishing compound for high shine", technicalCode: "POL-MET", material: "Polimer Bazlı", certification: "ISO 6344", price: 120, quantity: 250, inStock: true, specs: { hacim: "500 ml", bitirme: "Ayna", uygulama: "Manuel/Makine" }, specs_tr: { hacim: "500 ml", bitirme: "Ayna", uygulama: "Manuel/Makine" }, specs_en: { volume: "500 ml", finish: "Mirror", application: "Manual/Machine" }, datasheet: 'https://example.com/datasheets/POL-MET.pdf', image: 'https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop' },
  { id: 38, categoryId: "surface", name: "Aşındırıcı Kumlama Kumu - 80 mesh", name_tr: "Aşındırıcı Kumlama Kumu - 80 mesh", name_en: "Abrasive Blasting Sand - 80 mesh", description_tr: "Aşındırıcı kumlama için silika kumu", description_en: "Silica sand for abrasive blasting", technicalCode: "ABS-80", material: "Silika", certification: "ISO 11126", price: 65, quantity: 1200, inStock: true, specs: { granul: "80 mesh", saflık: "%99", yogunluk: "2.6 g/cm3" }, specs_tr: { granul: "80 mesh", saflık: "%99", yogunluk: "2.6 g/cm3" }, specs_en: { granule: "80 mesh", purity: "%99", density: "2.6 g/cm3" }, datasheet: 'https://example.com/datasheets/ABS-80.pdf', image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop' },
  { id: 39, categoryId: "surface", name: "Pas Dönüştürücü - 1L", name_tr: "Pas Dönüştürücü - 1L", name_en: "Rust Converter - 1L", description_tr: "Metal yüzeyler için kimyasal pas dönüştürücü", description_en: "Chemical rust converter for metal surfaces", technicalCode: "RUS-1L", material: "Kimyasal", certification: "ISO 12944", price: 95, quantity: 400, inStock: true, specs: { hacim: "1 L", kapsama: "10 m2", kuruma: "2 saat" }, specs_tr: { hacim: "1 L", kapsama: "10 m2", kuruma: "2 saat" }, specs_en: { volume: "1 L", coverage: "10 m2", drying: "2 hours" }, datasheet: 'https://example.com/datasheets/RUS-1L.pdf', image: 'https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop' },
  { id: 40, categoryId: "surface", name: "Metal Astarı - 500ml", name_tr: "Metal Astarı - 500ml", name_en: "Metal Primer - 500ml", description_tr: "Epoksi bazlı metal astarı", description_en: "Epoxy-based metal primer", technicalCode: "MET-PRM", material: "Epoksi", certification: "ISO 12944", price: 140, quantity: 350, inStock: true, specs: { hacim: "500 ml", kapsama: "8 m2", kuruma: "4 saat" }, specs_tr: { hacim: "500 ml", kapsama: "8 m2", kuruma: "4 saat" }, specs_en: { volume: "500 ml", coverage: "8 m2", drying: "4 hours" }, datasheet: 'https://example.com/datasheets/MET-PRM.pdf', image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop' },

  // Safety Equipment (41-50)
  { id: 41, categoryId: "safety", name: "Kevlar Dikişli Argon Eldiveni - L", name_tr: "Kevlar Dikişli Argon Eldiveni - L", name_en: "Kevlar-Stitched Argon Glove - L", description_tr: "Kevlar dikişli yüksek sıcaklık kaynakçı eldiveni", description_en: "High-temperature welding glove with Kevlar stitching", technicalCode: "KAG-L", material: "Deri", certification: "EN 12477", price: 180, quantity: 250, inStock: true, specs: { sicaklik: "500°C", boyut: "L", esneklik: "İyi" }, specs_tr: { sicaklik: "500°C", boyut: "L", esneklik: "İyi" }, specs_en: { temperature: "500°C", size: "L", flexibility: "Good" }, datasheet: 'https://example.com/datasheets/KAG-L.pdf', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop' },
  { id: 42, categoryId: "safety", name: "Kevlar Dikişli Argon Eldiveni - XL", name_tr: "Kevlar Dikişli Argon Eldiveni - XL", name_en: "Kevlar-Stitched Argon Glove - XL", description_tr: "Kevlar dikişli yüksek sıcaklık kaynakçı eldiveni", description_en: "High-temperature welding glove with Kevlar stitching", technicalCode: "KAG-XL", material: "Deri", certification: "EN 12477", price: 190, quantity: 200, inStock: true, specs: { sicaklik: "500°C", boyut: "XL", esneklik: "İyi" }, specs_tr: { sicaklik: "500°C", boyut: "XL", esneklik: "İyi" }, specs_en: { temperature: "500°C", size: "XL", flexibility: "Good" }, datasheet: 'https://example.com/datasheets/KAG-XL.pdf', image: 'https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop' },
  { id: 43, categoryId: "safety", name: "Aktif Karbon Gaz Maskesi - P100", name_tr: "Aktif Karbon Gaz Maskesi - P100", name_en: "Active Carbon Gas Mask - P100", description_tr: "P100 filtreli profesyonel gaz maskesi", description_en: "Professional gas mask with P100 filter", technicalCode: "ACM-P100", material: "Silikon", certification: "NIOSH", price: 280, quantity: 150, inStock: true, specs: { filter: "P100", koruma: "%99.97", suresi: "40 saat" }, specs_tr: { filter: "P100", koruma: "%99.97", suresi: "40 saat" }, specs_en: { filter: "P100", protection: "%99.97", duration: "40 hours" }, datasheet: 'https://example.com/datasheets/ACM-P100.pdf', image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop' },
  { id: 44, categoryId: "safety", name: "Aktif Karbon Gaz Maskesi - N95", name_tr: "Aktif Karbon Gaz Maskesi - N95", name_en: "Active Carbon Gas Mask - N95", description_tr: "N95 filtreli profesyonel gaz maskesi", description_en: "Professional gas mask with N95 filter", technicalCode: "ACM-N95", material: "Polipropilen", certification: "NIOSH", price: 45, quantity: 500, inStock: true, specs: { filter: "N95", koruma: "%95", suresi: "8 saat" }, specs_tr: { filter: "N95", koruma: "%95", suresi: "8 saat" }, specs_en: { filter: "N95", protection: "%95", duration: "8 hours" }, datasheet: 'https://example.com/datasheets/ACM-N95.pdf', image: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?q=80&w=800&auto=format&fit=crop' },
  { id: 45, categoryId: "safety", name: "Emniyet Gözlüğü - Koruyucu", name_tr: "Emniyet Gözlüğü - Koruyucu", name_en: "Safety Goggles - Protective", description_tr: "Darbe dirençli polikarbonat emniyet gözlüğü", description_en: "Impact-resistant polycarbonate safety goggles", technicalCode: "SG-PROT", material: "Polikarbonat", certification: "ANSI Z87.1", price: 65, quantity: 400, inStock: true, specs: { darbe: "Yüksek", uv: "Korumalı", sis: "Önleyici" }, specs_tr: { darbe: "Yüksek", uv: "Korumalı", sis: "Önleyici" }, specs_en: { impact: "High", uv: "Protected", fog: "Preventive" }, datasheet: 'https://example.com/datasheets/SG-PROT.pdf', image: 'https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop' },
  { id: 46, categoryId: "safety", name: "Emniyet Gözlüğü - Kaynakçı", name_tr: "Emniyet Gözlüğü - Kaynakçı", name_en: "Safety Goggles - Welding", description_tr: "UV korumalı koyu renkli kaynakçı gözlüğü", description_en: "Dark-tinted welding goggles with UV protection", technicalCode: "SG-WELD", material: "Polikarbonat", certification: "ANSI Z87.1", price: 85, quantity: 300, inStock: true, specs: { karanlık: "DIN 11", uv: "Tam Koruma", sis: "Önleyici" }, specs_tr: { karanlık: "DIN 11", uv: "Tam Koruma", sis: "Önleyici" }, specs_en: { darkness: "DIN 11", uv: "Full Protection", fog: "Preventive" }, datasheet: 'https://example.com/datasheets/SG-WELD.pdf', image: 'https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop' },
  { id: 47, categoryId: "safety", name: "Koruyucu Elbise - Tam Vücut", name_tr: "Koruyucu Elbise - Tam Vücut", name_en: "Protective Suit - Full Body", description_tr: "Yüksek sıcaklık çalışması için tam vücut koruyucu elbise", description_en: "Full-body protective suit for high-temperature work", technicalCode: "PS-FULL", material: "Alüminyum Kaplı Kumaş", certification: "EN 11612", price: 450, quantity: 100, inStock: true, specs: { sicaklik: "300°C", boyut: "M-XXL", renk: "Beyaz" }, specs_tr: { sicaklik: "300°C", boyut: "M-XXL", renk: "Beyaz" }, specs_en: { temperature: "300°C", size: "M-XXL", color: "White" }, datasheet: 'https://example.com/datasheets/PS-FULL.pdf', image: 'https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop' },
  { id: 48, categoryId: "safety", name: "Emniyet Ayakkabısı - Çelik Burunlu", name_tr: "Emniyet Ayakkabısı - Çelik Burunlu", name_en: "Safety Boots - Steel Toe", description_tr: "Çelik burunlu emniyet ayakkabısı", description_en: "Safety boots with steel toe cap", technicalCode: "SB-STEEL", material: "Deri", certification: "ISO 20345", price: 280, quantity: 200, inStock: true, specs: { burun: "Çelik", taban: "Kaymaz", boyut: "36-48" }, specs_tr: { burun: "Çelik", taban: "Kaymaz", boyut: "36-48" }, specs_en: { toe: "Steel", sole: "Non-slip", size: "36-48" }, datasheet: 'https://example.com/datasheets/SB-STEEL.pdf', image: 'https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop' },
  { id: 49, categoryId: "safety", name: "İşitme Koruyucu - Kulak Tıkacı", name_tr: "İşitme Koruyucu - Kulak Tıkacı", name_en: "Hearing Protector - Earplugs", description_tr: "İşitme koruması için yeniden kullanılabilir silikon kulak tıkacı", description_en: "Reusable silicone earplugs for hearing protection", technicalCode: "HP-EAR", material: "Silikon", certification: "ANSI S3.19", price: 35, quantity: 600, inStock: true, specs: { azaltma: "30 dB", malzeme: "Yumuşak", yeniden_kullanilabilir: "Evet" }, specs_tr: { azaltma: "30 dB", malzeme: "Yumuşak", yeniden_kullanilabilir: "Evet" }, specs_en: { reduction: "30 dB", material: "Soft", reusable: "Yes" }, datasheet: 'https://example.com/datasheets/HP-EAR.pdf', image: 'https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop' },
  { id: 50, categoryId: "safety", name: "Emniyet Miğferi - İnşaat", name_tr: "Emniyet Miğferi - İnşaat", name_en: "Safety Helmet - Construction", description_tr: "İnşaat sahası güvenliği için sert başlık", description_en: "Hard hat for construction site safety", technicalCode: "SH-CONST", material: "ABS", certification: "ANSI Z89.1", price: 75, quantity: 500, inStock: true, specs: { malzeme: "ABS", darbe: "Yüksek", havalandirma: "İyi" }, specs_tr: { malzeme: "ABS", darbe: "Yüksek", havalandirma: "İyi" }, specs_en: { material: "ABS", impact: "High", ventilation: "Good" }, datasheet: 'https://example.com/datasheets/SH-CONST.pdf', image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop' },
];
