export interface Product {
  id: number;
  categoryId: string;
  name: string;
  name_tr: string;
  name_en: string;
  description?: string;
  description_tr?: string;
  description_en?: string;
  technicalCode: string;
  material: string;
  certification: string;
  price: number;
  quantity: number;
  inStock: boolean;
  specs: Record<string, string>;
  specs_tr?: Record<string, string>;
  specs_en?: Record<string, string>;
  datasheet?: string;
  image?: string;
}

export interface Category {
  id: string;
  name: string;
  name_tr: string;
  name_en: string;
  slug: string;
  description: string;
  description_tr: string;
  description_en: string;
  icon: string;
}

export const categories: Category[] = [
  {
    id: "ndt",
    name: "NDT Sarfları",
    name_tr: "NDT Sarfları",
    name_en: "NDT Supplies",
    slug: "ndt",
    description: "Tahribatsız muayene malzemeleri ve test ekipmanları",
    description_tr: "Tahribatsız muayene malzemeleri ve test ekipmanları",
    description_en: "Non-destructive testing materials and inspection equipment",
    icon: "AlertCircle"
  },
  {
    id: "welding",
    name: "Kaynak & Alaşım",
    name_tr: "Kaynak & Alaşım",
    name_en: "Welding & Alloys",
    slug: "welding",
    description: "Özel kaynak telleri ve alaşım ürünleri",
    description_tr: "Özel kaynak telleri ve alaşım ürünleri",
    description_en: "Specialized welding wires and alloy products",
    icon: "Zap"
  },
  {
    id: "construction",
    name: "Yapı Kimyasalları",
    name_tr: "Yapı Kimyasalları",
    name_en: "Construction Chemicals",
    slug: "construction",
    description: "İleri yapı kimyasalları ve sabitleyiciler",
    description_tr: "İleri yapı kimyasalları ve sabitleyiciler",
    description_en: "Advanced construction chemicals and fasteners",
    icon: "Beaker"
  },
  {
    id: "surface",
    name: "Yüzey İşlem",
    name_tr: "Yüzey İşlem",
    name_en: "Surface Treatment",
    slug: "surface",
    description: "Yüzey işlem ve aşındırıcı ürünleri",
    description_tr: "Yüzey işlem ve aşındırıcı ürünleri",
    description_en: "Surface treatment and abrasive products",
    icon: "Wrench"
  },
  {
    id: "safety",
    name: "İş Güvenliği",
    name_tr: "İş Güvenliği",
    name_en: "Safety Equipment",
    slug: "safety",
    description: "Nitelikli iş güvenliği ekipmanları",
    description_tr: "Nitelikli iş güvenliği ekipmanları",
    description_en: "Qualified occupational safety equipment",
    icon: "Shield"
  }
];

export function getProductById(id: number): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter(p => p.categoryId === categoryId);
}

export const products: Product[] = [
  // --- NDT TEST EKİPMANLARI (1-15) ---
  {
    id: 1,
    categoryId: "ndt",
    name: "Penetrant Test Spreyi - Kırmızı 500ml",
    name_tr: "Penetrant Test Spreyi - Kırmızı 500ml",
    name_en: "Penetrant Test Spray - Red 500ml",
    description_tr: "Yüksek görünürlüklü, çatlak tespiti için kırmızı penetrant sıvısı.",
    description_en: "High-visibility red penetrant liquid for crack detection.",
    technicalCode: "YZN-NDT-001",
    material: "Kimyasal Çözücü",
    certification: "ISO 3452-2",
    price: 320,
    quantity: 500,
    inStock: true,
    specs: { hacim: "500ml", tip: "Tip II", hassasiyet: "Seviye 2" },
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 2,
    categoryId: "ndt",
    name: "Manyetik Parçacık Tozu - Siyah 1kg",
    name_tr: "Manyetik Parçacık Tozu - Siyah 1kg",
    name_en: "Magnetic Particle Powder - Black 1kg",
    description_tr: "Kuru yöntem manyetik parçacık muayenesi için yüksek kontrastlı toz.",
    description_en: "High-contrast powder for dry method magnetic particle inspection.",
    technicalCode: "YZN-NDT-002",
    material: "Demir Oksit",
    certification: "ASTM E1444",
    price: 450,
    quantity: 100,
    inStock: true,
    specs: { agirlik: "1kg", renk: "Siyah", sicaklik: "315°C" },
    image: "https://images.unsplash.com/photo-1530311701074-9ef4a446f62b?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 3,
    categoryId: "ndt",
    name: "Ultrasonik Muayene Jeli - 5 Litre",
    name_tr: "Ultrasonik Muayene Jeli - 5 Litre",
    name_en: "Ultrasonic Couplant Gel - 5L",
    description_tr: "Akustik iletimi maksimize eden, korozyon önleyici UT jeli.",
    description_en: "Anti-corrosive UT gel maximizing acoustic transmission.",
    technicalCode: "YZN-NDT-003",
    material: "Su Bazlı Polimer",
    certification: "ASTM E164",
    price: 280,
    quantity: 200,
    inStock: true,
    specs: { hacim: "5L", viskozite: "Yüksek", ph: "7.0" },
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 4,
    categoryId: "ndt",
    name: "UV-A LED El Lambası - Profesyonel",
    name_tr: "UV-A LED El Lambası - Profesyonel",
    name_en: "Professional UV-A LED Flashlight",
    description_tr: "Floresan penetrant ve manyetik parçacık testleri için 365nm UV lamba.",
    description_en: "365nm UV lamp for fluorescent penetrant and magnetic particle testing.",
    technicalCode: "YZN-NDT-004",
    material: "Alüminyum Gövde",
    certification: "CE / ISO 9001",
    price: 3250,
    quantity: 25,
    inStock: true,
    specs: { dalga_boyu: "365nm", guc: "10W", batarya: "Şarj Edilebilir" },
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 5,
    categoryId: "ndt",
    name: "Dijital Ultrasonik Kalınlık Ölçer",
    name_tr: "Dijital Ultrasonik Kalınlık Ölçer",
    name_en: "Digital Ultrasonic Thickness Gauge",
    description_tr: "Metal, plastik ve cam yüzeylerde hassas kalınlık ölçümü.",
    description_en: "Precision thickness measurement on metal, plastic, and glass surfaces.",
    technicalCode: "YZN-NDT-005",
    material: "Elektronik / ABS",
    certification: "EN 15317",
    price: 5800,
    quantity: 15,
    inStock: true,
    specs: { aralik: "1.0 - 300mm", hassasiyet: "0.01mm", ekran: "LCD" },
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 6,
    categoryId: "ndt",
    name: "Geliştirici Sprey (Developer) - Beyaz",
    name_tr: "Geliştirici Sprey (Developer) - Beyaz",
    name_en: "White Developer Spray",
    description_tr: "Penetrant sıvısını yüzeye çekerek çatlakları görünür kılan beyaz toz tabakası.",
    description_en: "White powder layer that draws penetrant to the surface to reveal cracks.",
    technicalCode: "YZN-NDT-006",
    material: "Solvent Bazlı",
    certification: "AMS 2644",
    price: 310,
    quantity: 450,
    inStock: true,
    specs: { hacim: "500ml", kuruma_hizi: "Hızlı", kalinti: "Düşük" },
    image: "https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 7,
    categoryId: "ndt",
    name: "Radyografik Film - Tip D7 10x40cm",
    name_tr: "Radyografik Film - Tip D7 10x40cm",
    name_en: "Radiographic Film - Type D7 10x40cm",
    description_tr: "Endüstriyel röntgen çekimleri için yüksek kontrastlı radyografik film.",
    description_en: "High-contrast radiographic film for industrial X-ray imaging.",
    technicalCode: "YZN-NDT-007",
    material: "Gümüş Halojenür",
    certification: "ISO 11699-1",
    price: 8400,
    quantity: 50,
    inStock: true,
    specs: { boyut: "10x40cm", paket: "100 Adet", sinif: "C5" },
    image: "https://images.unsplash.com/photo-1530210124550-912dc1381cb8?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 8,
    categoryId: "ndt",
    name: "Manyetik Yoke Cihazı - AC/DC",
    name_tr: "Manyetik Yoke Cihazı - AC/DC",
    name_en: "Magnetic Yoke - AC/DC",
    description_tr: "Yüzey çatlaklarını tespit etmek için taşınabilir elektromanyetik mıknatıs.",
    description_en: "Portable electromagnetic magnet for detecting surface cracks.",
    technicalCode: "YZN-NDT-008",
    material: "Çelik / Polimer",
    certification: "ASTM E709",
    price: 12500,
    quantity: 10,
    inStock: true,
    specs: { guc: "220V AC", kaldirma: "18kg (DC)", agirlik: "3.2kg" },
    image: "https://images.unsplash.com/photo-1581092162384-8987c1d64718?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 9,
    categoryId: "ndt",
    name: "Hassas Kumpas - 150mm Dijital",
    name_tr: "Hassas Kumpas - 150mm Dijital",
    name_en: "Precision Caliper - 150mm Digital",
    description_tr: "NDT öncesi ve sonrası parça boyut kontrolü için paslanmaz çelik kumpas.",
    description_en: "Stainless steel caliper for part size control before and after NDT.",
    technicalCode: "YZN-NDT-009",
    material: "Paslanmaz Çelik",
    certification: "DIN 862",
    price: 950,
    quantity: 60,
    inStock: true,
    specs: { aralik: "0-150mm", hassasiyet: "0.01mm", koruma: "IP54" },
    image: "https://images.unsplash.com/photo-1535813543266-73f83195c3e4?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 10,
    categoryId: "ndt",
    name: "V1 Kalibrasyon Bloğu - Karbon Çelik",
    name_tr: "V1 Kalibrasyon Bloğu - Karbon Çelik",
    name_en: "V1 Calibration Block - Carbon Steel",
    description_tr: "Ultrasonik test cihazlarının kalibrasyonu için standart referans bloğu.",
    description_en: "Standard reference block for calibration of ultrasonic testing equipment.",
    technicalCode: "YZN-NDT-010",
    material: "Karbon Çelik",
    certification: "EN ISO 2400",
    price: 2400,
    quantity: 20,
    inStock: true,
    specs: { tip: "V1 / IIW", malzeme: "S235JR", kaplama: "Nikel" },
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 11,
    categoryId: "ndt",
    name: "Eddy Current Yüzey Probu - 2MHz",
    name_tr: "Eddy Current Yüzey Probu - 2MHz",
    name_en: "Eddy Current Surface Probe - 2MHz",
    description_tr: "İletken malzemelerde yüzey altı çatlak tespiti için hassas prob.",
    description_en: "Precision probe for subsurface crack detection in conductive materials.",
    technicalCode: "YZN-NDT-011",
    material: "Seramik / Bakır",
    certification: "ISO 15549",
    price: 4800,
    quantity: 12,
    inStock: true,
    specs: { frekans: "2MHz", cap: "10mm", konnektör: "Microdot" },
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 12,
    categoryId: "ndt",
    name: "Lüksmetre - Dijital Işık Ölçer",
    name_tr: "Lüksmetre - Dijital Işık Ölçer",
    name_en: "Digital Lux Meter",
    description_tr: "Görsel muayene alanlarındaki ışık şiddetini ölçmek için dijital cihaz.",
    description_en: "Digital device to measure light intensity in visual inspection areas.",
    technicalCode: "YZN-NDT-012",
    material: "ABS Plastik",
    certification: "ISO 3059",
    price: 1150,
    quantity: 30,
    inStock: true,
    specs: { aralik: "0-200,000 Lux", hassasiyet: "%3", birim: "Lux / FC" },
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 13,
    categoryId: "ndt",
    name: "Sertlik Ölçüm Cihazı - Portatif Leeb",
    name_tr: "Sertlik Ölçüm Cihazı - Portatif Leeb",
    name_en: "Portable Leeb Hardness Tester",
    description_tr: "Ağır parçaların yerinde sertlik ölçümü için dijital darbe cihazı.",
    description_en: "Digital impact device for on-site hardness measurement of heavy parts.",
    technicalCode: "YZN-NDT-013",
    material: "Metal Alaşım",
    certification: "ASTM A956",
    price: 7200,
    quantity: 8,
    inStock: true,
    specs: { skalalar: "HRC, HRB, HB, HV", hafiza: "500 Grup", ekran: "OLED" },
    image: "https://images.unsplash.com/photo-1581092162384-8987c1d64718?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 14,
    categoryId: "ndt",
    name: "Vakum Kutusu - Kaynak Testi İçin",
    name_tr: "Vakum Kutusu - Kaynak Testi İçin",
    name_en: "Vacuum Box - For Weld Testing",
    description_tr: "Depolama tankı taban kaynaklarındaki sızıntı tespiti için vakum aparatı.",
    description_en: "Vacuum apparatus for leak detection in storage tank bottom welds.",
    technicalCode: "YZN-NDT-014",
    material: "Pleksiglas / Kauçuk",
    certification: "API 650",
    price: 8900,
    quantity: 5,
    inStock: true,
    specs: { boyut: "750mm", pompa: "Harici", conta: "Yumuşak Kauçuk" },
    image: "https://images.unsplash.com/photo-1535813543266-73f83195c3e4?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 15,
    categoryId: "ndt",
    name: "Sıcaklık Ölçer Tebeşir - 250°C",
    name_tr: "Sıcaklık Ölçer Tebeşir - 250°C",
    name_en: "Tempilstik Temperature Indicator - 250°C",
    description_tr: "Kaynak öncesi tavlama sıcaklığını kontrol etmek için eriyen tebeşir.",
    description_en: "Melting chalk to control preheat temperature before welding.",
    technicalCode: "YZN-NDT-015",
    material: "Termokromik Balmumu",
    certification: "NIST İzlenebilir",
    price: 185,
    quantity: 150,
    inStock: true,
    specs: { derece: "250°C", hassasiyet: "%1", paket: "Tekli" },
    image: "https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?q=80&w=800&auto=format&fit=crop"
  },

  // --- KAYNAK MALZEMELERİ (16-30) ---
  {
    id: 16,
    categoryId: "welding",
    name: "ER70S-6 Gazaltı Kaynak Teli 1.0mm 15kg",
    name_tr: "ER70S-6 Gazaltı Kaynak Teli 1.0mm 15kg",
    name_en: "ER70S-6 MIG Welding Wire 1.0mm 15kg",
    description_tr: "Genel imalat çelikleri için bakır kaplı yüksek kaliteli gazaltı teli.",
    description_en: "Copper-coated high-quality MIG wire for general fabrication steels.",
    technicalCode: "YZN-WELD-001",
    material: "Düşük Alaşımlı Çelik",
    certification: "AWS A5.18",
    price: 1850,
    quantity: 1000,
    inStock: true,
    specs: { cap: "1.0mm", agirlik: "15kg", makara: "Plastik/Hizli" },
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 17,
    categoryId: "welding",
    name: "E6013 Rutil Elektrod 3.25x350mm",
    name_tr: "E6013 Rutil Elektrod 3.25x350mm",
    name_en: "E6013 Rutile Electrode 3.25x350mm",
    description_tr: "Hafif çelik yapıların kaynağı için genel amaçlı rutil elektrod.",
    description_en: "General-purpose rutile electrode for welding mild steel structures.",
    technicalCode: "YZN-WELD-002",
    material: "Karbon Çelik",
    certification: "AWS A5.1",
    price: 420,
    quantity: 2000,
    inStock: true,
    specs: { boyut: "3.25x350mm", kutu: "5kg", akim: "90-130A" },
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 18,
    categoryId: "welding",
    name: "Paslanmaz TIG Teli 308L 2.4mm 5kg",
    name_tr: "Paslanmaz TIG Teli 308L 2.4mm 5kg",
    name_en: "Stainless TIG Wire 308L 2.4mm 5kg",
    description_tr: "304 ve 304L paslanmaz çeliklerin TIG kaynağı için dolgu teli.",
    description_en: "Filler wire for TIG welding of 304 and 304L stainless steels.",
    technicalCode: "YZN-WELD-003",
    material: "308L Paslanmaz Çelik",
    certification: "AWS A5.9",
    price: 2450,
    quantity: 300,
    inStock: true,
    specs: { cap: "2.4mm", uzunluk: "1000mm", paket: "5kg" },
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 19,
    categoryId: "welding",
    name: "Otomatik Kararan Kaynak Maskesi - 9-13 DIN",
    name_tr: "Otomatik Kararan Kaynak Maskesi - 9-13 DIN",
    name_en: "Auto-Darkening Welding Helmet - 9-13 DIN",
    description_tr: "Göz sağlığını koruyan, hızlı kararma özellikli profesyonel kaynak maskesi.",
    description_en: "Professional welding helmet with fast darkening to protect eye health.",
    technicalCode: "YZN-WELD-004",
    material: "Yüksek Darbe Polimer",
    certification: "ANSI Z87.1 / EN 379",
    price: 2150,
    quantity: 80,
    inStock: true,
    specs: { sensor: "4 Adet", guc: "Güneş Pili + Pil", hizi: "1/25,000s" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 20,
    categoryId: "welding",
    name: "Argon Gaz Regülatörü - Pirinç Gövde",
    name_tr: "Argon Gaz Regülatörü - Pirinç Gövde",
    name_en: "Argon Gas Regulator - Brass Body",
    description_tr: "TIG ve MIG kaynaklarında hassas gaz debi kontrolü sağlayan regülatör.",
    description_en: "Regulator providing precise gas flow control in TIG and MIG welding.",
    technicalCode: "YZN-WELD-005",
    material: "Dövme Pirinç",
    certification: "EN ISO 2503",
    price: 1350,
    quantity: 120,
    inStock: true,
    specs: { giris: "230 Bar", cikis: "0-32 L/dk", baglanti: "W21.8 x 1/14" },
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 21,
    categoryId: "welding",
    name: "Kaynak Battaniyesi - 2x2m Yanmaz Silis",
    name_tr: "Kaynak Battaniyesi - 2x2m Yanmaz Silis",
    name_en: "Welding Blanket - 2x2m Fireproof Silica",
    description_tr: "Çalışma alanını kaynak sıçrantılarından koruyan yüksek sıcaklık battaniyesi.",
    description_en: "High-temperature blanket protecting work area from welding spatters.",
    technicalCode: "YZN-WELD-006",
    material: "Silika Kumaş",
    certification: "EN 13501-1",
    price: 2850,
    quantity: 45,
    inStock: true,
    specs: { boyut: "2x2m", sicaklik: "1000°C Sürekli", kalınlık: "0.7mm" },
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 22,
    categoryId: "welding",
    name: "TIG Kaynak Torcu - 4m Hava Soğutmalı",
    name_tr: "TIG Kaynak Torcu - 4m Hava Soğutmalı",
    name_en: "TIG Welding Torch - 4m Air Cooled",
    description_tr: "Esnek kablo yapısına sahip, ergonomik TIG kaynak torcu.",
    description_en: "Ergonomic TIG welding torch with flexible cable structure.",
    technicalCode: "YZN-WELD-007",
    material: "Bakır / Kauçuk",
    certification: "IEC 60974-7",
    price: 3400,
    quantity: 35,
    inStock: true,
    specs: { uzunluk: "4m", akim: "200A DC", tip: "WP-26" },
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 23,
    categoryId: "welding",
    name: "Kaynakçı Pensesi - 500A Profesyonel",
    name_tr: "Kaynakçı Pensesi - 500A Profesyonel",
    name_en: "Electrode Holder - 500A Professional",
    description_tr: "Elektrot kaynağı için yüksek iletkenlikli, ısınmayan pense.",
    description_en: "High-conductivity, non-heating holder for electrode welding.",
    technicalCode: "YZN-WELD-008",
    material: "Pirinç / Fiberglas",
    certification: "EN 60974-11",
    price: 480,
    quantity: 150,
    inStock: true,
    specs: { kapasite: "500A", kablo: "50-95mm2", yay: "Güçlendirilmiş" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 24,
    categoryId: "welding",
    name: "Kaynak Sıçrantı Önleyici Sprey - 400ml",
    name_tr: "Kaynak Sıçrantı Önleyici Sprey - 400ml",
    name_en: "Anti-Spatter Spray - 400ml",
    description_tr: "Sıçrantıların metale yapışmasını engelleyen silikonsuz sprey.",
    description_en: "Silicone-free spray preventing spatters from adhering to metal.",
    technicalCode: "YZN-WELD-009",
    material: "Su Bazlı",
    certification: "REACH Uyumlu",
    price: 145,
    quantity: 600,
    inStock: true,
    specs: { hacim: "400ml", silikon: "Yok", boyanabilir: "Evet" },
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 25,
    categoryId: "welding",
    name: "Manyetik Kaynak Gönyesi - 22kg",
    name_tr: "Manyetik Kaynak Gönyesi - 22kg",
    name_en: "Magnetic Welding Square - 22kg",
    description_tr: "Parçaları kaynak öncesi 45, 90 ve 135 derecelerde sabit tutan mıknatıs.",
    description_en: "Magnet holding parts at 45, 90, and 135 degrees before welding.",
    technicalCode: "YZN-WELD-010",
    material: "Ferrit Mıknatıs / Çelik",
    certification: "CE",
    price: 320,
    quantity: 250,
    inStock: true,
    specs: { guc: "22kg", acilar: "45°, 90°, 135°", boyut: "Büyük" },
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 26,
    categoryId: "welding",
    name: "Alüminyum Kaynak Teli 5356 1.2mm 7kg",
    name_tr: "Alüminyum Kaynak Teli 5356 1.2mm 7kg",
    name_en: "Aluminum Welding Wire 5356 1.2mm 7kg",
    description_tr: "Denizcilik ve yapısal uygulamalar için yüksek dayanımlı alüminyum teli.",
    description_en: "High-strength aluminum wire for marine and structural applications.",
    technicalCode: "YZN-WELD-011",
    material: "AlMg5 Alaşımı",
    certification: "AWS A5.10",
    price: 3100,
    quantity: 180,
    inStock: true,
    specs: { cap: "1.2mm", agirlik: "7kg", makara: "S300" },
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 27,
    categoryId: "welding",
    name: "Seramik Kaynak Altlığı - 12mm Düz",
    name_tr: "Seramik Kaynak Altlığı - 12mm Düz",
    name_en: "Ceramic Welding Backing - 12mm Flat",
    description_tr: "Tek taraflı kaynaklarda kök pasosu kalitesini artıran seramik altlık.",
    description_en: "Ceramic backing improving root pass quality in single-sided welding.",
    technicalCode: "YZN-WELD-012",
    material: "Kordiyerit Seramik",
    certification: "ISO 9001",
    price: 85,
    quantity: 1200,
    inStock: true,
    specs: { genislik: "12mm", uzunluk: "600mm", bant: "Alüminyum" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 28,
    categoryId: "welding",
    name: "Wolfram Elektrod - %2 Lantanyumlu (Mavi)",
    name_tr: "Wolfram Elektrod - %2 Lantanyumlu (Mavi)",
    name_en: "Tungsten Electrode - 2% Lanthanated (Blue)",
    description_tr: "TIG kaynağı için uzun ömürlü, radyoaktif olmayan wolfram elektrod.",
    description_en: "Long-lasting, non-radioactive tungsten electrode for TIG welding.",
    technicalCode: "YZN-WELD-013",
    material: "Wolfram + %2 La2O3",
    certification: "ISO 6848",
    price: 1150,
    quantity: 500,
    inStock: true,
    specs: { cap: "2.4mm", uzunluk: "175mm", paket: "10 Adet" },
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 29,
    categoryId: "welding",
    name: "Kaynak Kablosu - 50mm2 Saf Bakır",
    name_tr: "Kaynak Kablosu - 50mm2 Saf Bakır",
    name_en: "Welding Cable - 50mm2 Pure Copper",
    description_tr: "Yüksek akım taşıma kapasiteli, esnek kauçuk kaplı kaynak kablosu.",
    description_en: "Flexible rubber-coated welding cable with high current carrying capacity.",
    technicalCode: "YZN-WELD-014",
    material: "Elektrolitik Bakır",
    certification: "H01N2-D",
    price: 450,
    quantity: 1000,
    inStock: true,
    specs: { kesit: "50mm2", kaplama: "Neopren", birim: "Metre" },
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 30,
    categoryId: "welding",
    name: "Gazaltı Kaynak Nozulu - Konik Tip",
    name_tr: "Gazaltı Kaynak Nozulu - Konik Tip",
    name_en: "MIG Welding Nozzle - Conical Type",
    description_tr: "MIG/MAG torçları için gaz akışını yönlendiren bakır nozul.",
    description_en: "Copper nozzle directing gas flow for MIG/MAG torches.",
    technicalCode: "YZN-WELD-015",
    material: "Bakır Alaşımı",
    certification: "OEM Uyumlu",
    price: 120,
    quantity: 400,
    inStock: true,
    specs: { tip: "Konik", uyum: "Binzel MB25", adet: "5'li Paket" },
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop"
  },

  // --- YÜZEY İŞLEM (31-45) ---
  {
    id: 31,
    categoryId: "surface",
    name: "Grit G40 Kumlama Kumu 25kg",
    name_tr: "Grit G40 Kumlama Kumu 25kg",
    name_en: "Grit G40 Blasting Abrasive 25kg",
    description_tr: "Ağır pas ve boya sökümü için yüksek aşındırıcılı çelik grit.",
    description_en: "High-abrasive steel grit for heavy rust and paint removal.",
    technicalCode: "YZN-SURF-001",
    material: "Çelik Grit",
    certification: "ISO 11124",
    price: 1250,
    quantity: 2000,
    inStock: true,
    specs: { boyut: "0.4 - 1.0mm", sertlik: "60-66 HRC", agirlik: "25kg" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 32,
    categoryId: "surface",
    name: "Zirkonyum Flap Disk 115mm P60",
    name_tr: "Zirkonyum Flap Disk 115mm P60",
    name_en: "Zirconia Flap Disk 115mm P60",
    description_tr: "Paslanmaz ve alaşımlı çeliklerin taşlanması için uzun ömürlü flap disk.",
    description_en: "Long-lasting flap disk for grinding stainless and alloy steels.",
    technicalCode: "YZN-SURF-002",
    material: "Zirkonyum Alümina",
    certification: "OSA / EN 13743",
    price: 65,
    quantity: 5000,
    inStock: true,
    specs: { cap: "115mm", kum: "60", max_rpm: "13,300" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 33,
    categoryId: "surface",
    name: "Cam Küreciği (Glass Bead) 100-200 mic",
    name_tr: "Cam Küreciği (Glass Bead) 100-200 mic",
    name_en: "Glass Beads 100-200 mic",
    description_tr: "Hassas yüzey temizliği ve satin bitiş için cam kumlama malzemesi.",
    description_en: "Glass blasting media for precision surface cleaning and satin finish.",
    technicalCode: "YZN-SURF-003",
    material: "Sodyum Kireç Camı",
    certification: "ISO 11126-10",
    price: 1100,
    quantity: 1500,
    inStock: true,
    specs: { boyut: "100-200 mic", sertlik: "6 Mohs", agirlik: "25kg" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 34,
    categoryId: "surface",
    name: "Pas Sökücü ve Dönüştürücü Jel 1kg",
    name_tr: "Pas Sökücü ve Dönüştürücü Jel 1kg",
    name_en: "Rust Remover and Converter Gel 1kg",
    description_tr: "Paslı yüzeyleri temizleyen ve boyaya hazır hale getiren asidik jel.",
    description_en: "Acidic gel that cleans rusted surfaces and prepares them for painting.",
    technicalCode: "YZN-SURF-004",
    material: "Fosforik Asit Bazlı",
    certification: "MSDS Mevcut",
    price: 340,
    quantity: 400,
    inStock: true,
    specs: { agirlik: "1kg", uygulama: "Fırça/Rulo", etki: "15-30 dk" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 35,
    categoryId: "surface",
    name: "Tel Çanak Fırça 75mm - Burgulu",
    name_tr: "Tel Çanak Fırça 75mm - Burgulu",
    name_en: "Twisted Wire Cup Brush 75mm",
    description_tr: "Avuç taşlama makineleri için agresif temizlik sağlayan burgulu tel fırça.",
    description_en: "Twisted wire brush providing aggressive cleaning for angle grinders.",
    technicalCode: "YZN-SURF-005",
    material: "Çelik Tel",
    certification: "DIN 68347",
    price: 185,
    quantity: 800,
    inStock: true,
    specs: { cap: "75mm", baglanti: "M14", tel_tipi: "0.50mm Burgulu" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 36,
    categoryId: "surface",
    name: "Alüminyum Oksit Kumlama Kumu 25kg",
    name_tr: "Alüminyum Oksit Kumlama Kumu 25kg",
    name_en: "Aluminum Oxide Abrasive 25kg",
    description_tr: "Yüksek sertlikte, tekrar kullanılabilir kahverengi alüminyum oksit.",
    description_en: "High-hardness, reusable brown aluminum oxide.",
    technicalCode: "YZN-SURF-006",
    material: "Korundum",
    certification: "FEPA Standart",
    price: 1950,
    quantity: 1200,
    inStock: true,
    specs: { boyut: "F24 - F120", saflik: "%95 Al2O3", agirlik: "25kg" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 37,
    categoryId: "surface",
    name: "Saten Parlatma Tekerleği 110x100mm",
    name_tr: "Saten Parlatma Tekerleği 110x100mm",
    name_en: "Satin Polishing Wheel 110x100mm",
    description_tr: "Paslanmaz yüzeylerde dekoratif saten bitiş sağlayan mop tekerlek.",
    description_en: "Mop wheel providing decorative satin finish on stainless surfaces.",
    technicalCode: "YZN-SURF-007",
    material: "Aşındırıcı Elyaf",
    certification: "ISO 9001",
    price: 420,
    quantity: 150,
    inStock: true,
    specs: { boyut: "110x100mm", kum: "Medium", mil: "19mm" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 38,
    categoryId: "surface",
    name: "Yüzey Temizleme Solventi 5L",
    name_tr: "Yüzey Temizleme Solventi 5L",
    name_en: "Surface Cleaning Solvent 5L",
    description_tr: "Boya ve kaplama öncesi yağ ve gres temizliği için hızlı solvent.",
    description_en: "Fast solvent for oil and grease cleaning before painting and coating.",
    technicalCode: "YZN-SURF-008",
    material: "Hidrokarbon Karışımı",
    certification: "UN 1263",
    price: 580,
    quantity: 300,
    inStock: true,
    specs: { hacim: "5L", buharlasmas: "Hızlı", kalinti: "Yok" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 39,
    categoryId: "surface",
    name: "Fiber Disk 180mm P36",
    name_tr: "Fiber Disk 180mm P36",
    name_en: "Fiber Disc 180mm P36",
    description_tr: "Ağır talaş kaldırma ve kaynak dikişi taşlama için fiber tabanlı disk.",
    description_en: "Fiber-based disc for heavy stock removal and weld seam grinding.",
    technicalCode: "YZN-SURF-009",
    material: "Seramik Taneli",
    certification: "EN 13743",
    price: 45,
    quantity: 2500,
    inStock: true,
    specs: { cap: "180mm", kum: "36", paket: "25 Adet" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 40,
    categoryId: "surface",
    name: "Polisaj Pastası - Mavi (Parlatma)",
    name_tr: "Polisaj Pastası - Mavi (Parlatma)",
    name_en: "Polishing Compound - Blue (Finishing)",
    description_tr: "Metal yüzeylerde ayna parlaklığı elde etmek için son kat polisaj pastası.",
    description_en: "Final coat polishing compound to achieve mirror shine on metal surfaces.",
    technicalCode: "YZN-SURF-010",
    material: "Sentetik Mum / Aşındırıcı",
    certification: "TSE Uyumlu",
    price: 210,
    quantity: 600,
    inStock: true,
    specs: { agirlik: "800g", renk: "Mavi", uygulama: "Bez fırça" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 41,
    categoryId: "surface",
    name: "Kumlama Nozulu - Bor Karbür 6mm",
    name_tr: "Kumlama Nozulu - Bor Karbür 6mm",
    name_en: "Blasting Nozzle - Boron Carbide 6mm",
    description_tr: "Aşırı aşınmaya dayanıklı, uzun ömürlü bor karbür kumlama nozulu.",
    description_en: "Long-lasting boron carbide blasting nozzle resistant to extreme wear.",
    technicalCode: "YZN-SURF-011",
    material: "Bor Karbür (B4C)",
    certification: "ISO 9001",
    price: 4600,
    quantity: 20,
    inStock: true,
    specs: { cap: "6mm", uzunluk: "150mm", kilif: "Alüminyum" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 42,
    categoryId: "surface",
    name: "Yüzey Pürüzlülük Karşılaştırma Plakası",
    name_tr: "Yüzey Pürüzlülük Karşılaştırma Plakası",
    name_en: "Surface Roughness Comparator",
    description_tr: "Kumlama sonrası yüzey pürüzlülüğünü görsel olarak kontrol etmek için plaka.",
    description_en: "Plate to visually check surface roughness after blasting.",
    technicalCode: "YZN-SURF-012",
    material: "Nikel Alaşım",
    certification: "ISO 8503",
    price: 1850,
    quantity: 15,
    inStock: true,
    specs: { tip: "G (Grit)", siniflar: "Fine, Medium, Coarse", paket: "Deri Kılıf" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 43,
    categoryId: "surface",
    name: "Pneumatik İğneli Çapak Alma Tabancası",
    name_tr: "Pneumatik İğneli Çapak Alma Tabancası",
    name_en: "Pneumatic Needle Scaler",
    description_tr: "Kaynak çapağı ve pas temizliği için hava tahrikli iğneli tabanca.",
    description_en: "Air-driven needle scaler for weld spatter and rust cleaning.",
    technicalCode: "YZN-SURF-013",
    material: "Çelik / Kompozit",
    certification: "CE / EN 792",
    price: 5400,
    quantity: 10,
    inStock: true,
    specs: { igne_sayisi: "19", darbe: "4000 bpm", hava: "6.3 Bar" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 44,
    categoryId: "surface",
    name: "Elektrostatik Toz Boya Tabancası",
    name_tr: "Elektrostatik Toz Boya Tabancası",
    name_en: "Electrostatic Powder Coating Gun",
    description_tr: "Endüstriyel metal parçaların toz boya ile kaplanması için manuel sistem.",
    description_en: "Manual system for coating industrial metal parts with powder paint.",
    technicalCode: "YZN-SURF-014",
    material: "Polimer / Metal",
    certification: "ATEX",
    price: 18500,
    quantity: 4,
    inStock: true,
    specs: { voltaj: "100kV", debi: "600g/dk", tip: "Corona" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 45,
    categoryId: "surface",
    name: "Boya Kalınlık Ölçüm Cihazı - Dijital",
    name_tr: "Boya Kalınlık Ölçüm Cihazı - Dijital",
    name_en: "Digital Coating Thickness Gauge",
    description_tr: "Demir ve demir dışı metaller üzerindeki boya kalınlığını ölçen cihaz.",
    description_en: "Device measuring coating thickness on ferrous and non-ferrous metals.",
    technicalCode: "YZN-SURF-015",
    material: "ABS / Elektronik",
    certification: "ISO 2178",
    price: 3200,
    quantity: 25,
    inStock: true,
    specs: { aralik: "0-2000 um", hassasiyet: "%2", prob: "F & N" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },

  // --- İŞ GÜVENLİĞİ (46-60) ---
  {
    id: 46,
    categoryId: "safety",
    name: "Nitril Kaplı Kesilmez İş Eldiveni - No:10",
    name_tr: "Nitril Kaplı Kesilmez İş Eldiveni - No:10",
    name_en: "Nitrile Coated Cut Resistant Glove - Size 10",
    description_tr: "Keskin metal parçalarla çalışma için yüksek korumalı iş eldiveni.",
    description_en: "High-protection work glove for working with sharp metal parts.",
    technicalCode: "YZN-SAFE-001",
    material: "HPPE / Nitril",
    certification: "EN 388:2016 (4X43D)",
    price: 125,
    quantity: 5000,
    inStock: true,
    specs: { beden: "10 (XL)", kesilmezlik: "D Seviyesi", paket: "12 Çift" },
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 47,
    categoryId: "safety",
    name: "Aktif Karbon Gaz Maskesi - Çift Filtreli",
    name_tr: "Aktif Karbon Gaz Maskesi - Çift Filtreli",
    name_en: "Double Filter Active Carbon Gas Mask",
    description_tr: "Boya ve kimyasal buharlarına karşı tam koruma sağlayan yarım yüz maske.",
    description_en: "Half-face mask providing full protection against paint and chemical vapors.",
    technicalCode: "YZN-SAFE-002",
    material: "TPE / Silikon",
    certification: "EN 140",
    price: 850,
    quantity: 200,
    inStock: true,
    specs: { filtre: "A1P2", baglanti: "Bayonet", agirlik: "380g" },
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 48,
    categoryId: "safety",
    name: "Emniyet Gözlüğü - Buğulanmaz Şeffaf",
    name_tr: "Emniyet Gözlüğü - Buğulanmaz Şeffaf",
    name_en: "Anti-Fog Clear Safety Goggles",
    description_tr: "Çizilmeye dayanıklı, UV korumalı ve buğulanmaz lensli emniyet gözlüğü.",
    description_en: "Scratch-resistant, UV-protected safety goggles with anti-fog lens.",
    technicalCode: "YZN-SAFE-003",
    material: "Polikarbonat",
    certification: "EN 166 1FT",
    price: 95,
    quantity: 1200,
    inStock: true,
    specs: { lens: "Şeffaf", kaplama: "K&N", sap: "Ayarlanabilir" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 49,
    categoryId: "safety",
    name: "Çelik Burunlu İş Botu - S3 SRC",
    name_tr: "Çelik Burunlu İş Botu - S3 SRC",
    name_en: "Steel Toe Work Boots - S3 SRC",
    description_tr: "Suya dayanıklı deri, çelik burun ve ara tabanlı yüksek güvenlikli bot.",
    description_en: "Water-resistant leather, steel toe and midsole high-security boots.",
    technicalCode: "YZN-SAFE-004",
    material: "Cilt Deri",
    certification: "EN ISO 20345:2011",
    price: 1450,
    quantity: 600,
    inStock: true,
    specs: { beden: "38-46", koruma: "S3", taban: "PU/PU Çift Dansite" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 50,
    categoryId: "safety",
    name: "Gürültü Önleyici Kulaklık - 32dB",
    name_tr: "Gürültü Önleyici Kulaklık - 32dB",
    name_en: "Noise Cancelling Earmuffs - 32dB",
    description_tr: "Yüksek gürültülü endüstriyel ortamlarda işitme koruması için kulaklık.",
    description_en: "Earmuffs for hearing protection in high-noise industrial environments.",
    technicalCode: "YZN-SAFE-005",
    material: "ABS / Sentetik Deri",
    certification: "EN 352-1",
    price: 480,
    quantity: 350,
    inStock: true,
    specs: { azaltma: "32dB SNR", agirlik: "240g", yapi: "Katlanabilir" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 51,
    categoryId: "safety",
    name: "Mühendis Tipi Emniyet Bareti - Beyaz",
    name_tr: "Mühendis Tipi Emniyet Bareti - Beyaz",
    name_en: "Engineer Type Safety Helmet - White",
    description_tr: "Havalandırmalı, 6 noktadan bağlantılı, konforlu koruyucu baret.",
    description_en: "Ventilated, 6-point connection, comfortable protective helmet.",
    technicalCode: "YZN-SAFE-006",
    material: "HDPE",
    certification: "EN 397",
    price: 220,
    quantity: 800,
    inStock: true,
    specs: { renk: "Beyaz", kullanim: "5 Yıl", ayar: "Vidalı" },
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 52,
    categoryId: "safety",
    name: "Yüksek Görünürlüklü İkaz Yeleği - Turuncu",
    name_tr: "Yüksek Görünürlüklü İkaz Yeleği - Turuncu",
    name_en: "High-Visibility Warning Vest - Orange",
    description_tr: "Reflektörlü şeritlere sahip, EN 20471 standartlı iş güvenliği yeleği.",
    description_en: "Safety vest with reflective strips, EN 20471 standard compliant.",
    technicalCode: "YZN-SAFE-007",
    material: "%100 Polyester",
    certification: "EN ISO 20471",
    price: 85,
    quantity: 2500,
    inStock: true,
    specs: { sinif: "Sınıf 2", reflektör: "3M", beden: "L/XL" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 53,
    categoryId: "safety",
    name: "FFP3 Ventilli Toz Maskesi - 10'lu Paket",
    name_tr: "FFP3 Ventilli Toz Maskesi - 10'lu Paket",
    name_en: "FFP3 Valved Dust Mask - Pack of 10",
    description_tr: "İnce toz ve nükleer partiküllere karşı en yüksek seviye koruma.",
    description_en: "Highest level protection against fine dust and nuclear particles.",
    technicalCode: "YZN-SAFE-008",
    material: "Dokumasız Kumaş",
    certification: "EN 149:2001+A1:2009",
    price: 650,
    quantity: 1000,
    inStock: true,
    specs: { koruma: "FFP3", ventil: "Var", paket: "10 Adet" },
    image: "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 54,
    categoryId: "safety",
    name: "Deri Kaynakçı Önlüğü - Isıya Dayanıklı",
    name_tr: "Deri Kaynakçı Önlüğü - Isıya Dayanıklı",
    name_en: "Leather Welder's Apron - Heat Resistant",
    description_tr: "Yarma deriden imal edilmiş, kaynak sıçrantılarına karşı gövde koruması.",
    description_en: "Split leather apron for torso protection against welding spatters.",
    technicalCode: "YZN-SAFE-009",
    material: "Sığır Yarma Deri",
    certification: "EN ISO 11611",
    price: 580,
    quantity: 150,
    inStock: true,
    specs: { boyut: "60x90cm", dikis: "Kevlar", kalınlık: "1.2mm" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 55,
    categoryId: "safety",
    name: "Paraşüt Tipi Emniyet Kemeri - Tam Vücut",
    name_tr: "Paraşüt Tipi Emniyet Kemeri - Tam Vücut",
    name_en: "Full Body Safety Harness",
    description_tr: "Yüksekte çalışma için çift lanyart bağlantılı emniyet kemeri.",
    description_en: "Full body harness with double lanyard connection for working at heights.",
    technicalCode: "YZN-SAFE-010",
    material: "Polyester Kolon",
    certification: "EN 361",
    price: 1850,
    quantity: 120,
    inStock: true,
    specs: { baglanti: "Sırt & Göğüs", tokalar: "Hızlı Ayar", yapi: "Ergonomik" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 56,
    categoryId: "safety",
    name: "Yüz Koruyucu Siperlik - Şeffaf",
    name_tr: "Yüz Koruyucu Siperlik - Şeffaf",
    name_en: "Face Shield - Clear",
    description_tr: "Sıvı sıçraması ve metal çapaklarına karşı tam yüz koruması.",
    description_en: "Full face protection against liquid splashes and metal chips.",
    technicalCode: "YZN-SAFE-011",
    material: "Polikarbonat / ABS",
    certification: "EN 166",
    price: 240,
    quantity: 400,
    inStock: true,
    specs: { siper: "20x40cm", ayar: "Mekanizmalı", koruma: "Darbe" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 57,
    categoryId: "safety",
    name: "Tek Kullanımlık Tyvek Tulum - Tip 5/6",
    name_tr: "Tek Kullanımlık Tyvek Tulum - Tip 5/6",
    name_en: "Disposable Tyvek Coverall - Type 5/6",
    description_tr: "Tehlikeli toz ve hafif kimyasal sıçramalarına karşı koruyucu tulum.",
    description_en: "Protective coverall against hazardous dust and light chemical splashes.",
    technicalCode: "YZN-SAFE-012",
    material: "Tyvek / Polietilen",
    certification: "EN 14126",
    price: 165,
    quantity: 1500,
    inStock: true,
    specs: { tip: "5 & 6", beden: "L-XXL", antistatik: "Evet" },
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 58,
    categoryId: "safety",
    name: "Göz Duşu İstasyonu - Duvara Monte",
    name_tr: "Göz Duşu İstasyonu - Duvara Monte",
    name_en: "Eye Wash Station - Wall Mounted",
    description_tr: "Kimyasal temasında acil müdahale için çift çıkışlı göz duşu.",
    description_en: "Double outlet eye wash for emergency response in chemical contact.",
    technicalCode: "YZN-SAFE-013",
    material: "Paslanmaz Çelik / ABS",
    certification: "ANSI Z358.1",
    price: 3850,
    quantity: 25,
    inStock: true,
    specs: { debi: "11.4 L/dk", aktivasyon: "El/Ayak", montaj: "Duvar" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 59,
    categoryId: "safety",
    name: "Kevlar Dikişli Kaynakçı Eldiveni - 35cm",
    name_tr: "Kevlar Dikişli Kaynakçı Eldiveni - 35cm",
    name_en: "Welding Glove with Kevlar Stitching - 35cm",
    description_tr: "Isıya dayanıklı, uzun konçlu, ağır hizmet kaynakçı eldiveni.",
    description_en: "Heat-resistant, long-cuff, heavy-duty welder's glove.",
    technicalCode: "YZN-SAFE-014",
    material: "Isıl İşlem Görmüş Deri",
    certification: "EN 12477 Tip A",
    price: 310,
    quantity: 1200,
    inStock: true,
    specs: { uzunluk: "35cm", dikis: "Kevlar", astar: "%100 Pamuk" },
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 60,
    categoryId: "safety",
    name: "İş Güvenliği Uyarı Levhası - 25x35cm",
    name_tr: "İş Güvenliği Uyarı Levhası - 25x35cm",
    name_en: "Safety Warning Sign - 25x35cm",
    description_tr: "Saha güvenliği için uyarıcı ve bilgilendirici PVC levha.",
    description_en: "Warning and informative PVC sign for site safety.",
    technicalCode: "YZN-SAFE-015",
    material: "PVC / Dekota",
    certification: "ISO 7010",
    price: 45,
    quantity: 3000,
    inStock: true,
    specs: { boyut: "25x35cm", kalınlık: "3mm", baskı: "UV" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  }
];
