export interface Product {
  id: number;
  categoryId: string;
  name: string;
  name_tr: string;
  name_en: string;
  description?: string;
  description_tr?: string;
  description_en?: string;
  technicalCode: string;
  material: string;
  certification: string;
  price: number;
  quantity: number;
  inStock: boolean;
  specs: Record<string, string>;
  specs_tr?: Record<string, string>;
  specs_en?: Record<string, string>;
  datasheet?: string;
  image?: string;
}

export interface Category {
  id: string;
  name: string;
  name_tr: string;
  name_en: string;
  slug: string;
  description: string;
  description_tr: string;
  description_en: string;
  icon: string;
}

export const categories: Category[] = [
  {
    id: "ndt",
    name: "NDT Sarfları",
    name_tr: "NDT Sarfları",
    name_en: "NDT Supplies",
    slug: "ndt",
    description: "Tahribatsız muayene malzemeleri ve test ekipmanları",
    description_tr: "Tahribatsız muayene malzemeleri ve test ekipmanları",
    description_en: "Non-destructive testing materials and inspection equipment",
    icon: "AlertCircle"
  },
  {
    id: "welding",
    name: "Kaynak & Alaşım",
    name_tr: "Kaynak & Alaşım",
    name_en: "Welding & Alloys",
    slug: "welding",
    description: "Özel kaynak telleri ve alaşım ürünleri",
    description_tr: "Özel kaynak telleri ve alaşım ürünleri",
    description_en: "Specialized welding wires and alloy products",
    icon: "Zap"
  },
  {
    id: "construction",
    name: "Yapı Kimyasalları",
    name_tr: "Yapı Kimyasalları",
    name_en: "Construction Chemicals",
    slug: "construction",
    description: "İleri yapı kimyasalları ve sabitleyiciler",
    description_tr: "İleri yapı kimyasalları ve sabitleyiciler",
    description_en: "Advanced construction chemicals and fasteners",
    icon: "Beaker"
  },
  {
    id: "surface",
    name: "Yüzey İşlem",
    name_tr: "Yüzey İşlem",
    name_en: "Surface Treatment",
    slug: "surface",
    description: "Yüzey işlem ve aşındırıcı ürünleri",
    description_tr: "Yüzey işlem ve aşındırıcı ürünleri",
    description_en: "Surface treatment and abrasive products",
    icon: "Wrench"
  },
  {
    id: "safety",
    name: "İş Güvenliği",
    name_tr: "İş Güvenliği",
    name_en: "Safety Equipment",
    slug: "safety",
    description: "Nitelikli iş güvenliği ekipmanları",
    description_tr: "Nitelikli iş güvenliği ekipmanları",
    description_en: "Qualified occupational safety equipment",
    icon: "Shield"
  }
];

export function getProductById(id: number): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter(p => p.categoryId === categoryId);
}

export const products: Product[] = [
  // --- NDT TEST EKİPMANLARI (1-15) ---
  {
    id: 1,
    categoryId: "ndt",
    name: "Penetrant Test Spreyi - Kırmızı 500ml",
    name_tr: "Penetrant Test Spreyi - Kırmızı 500ml",
    name_en: "Penetrant Test Spray - Red 500ml",
    description_tr: "Yüksek görünürlüklü, çatlak tespiti için kırmızı penetrant sıvısı.",
    description_en: "High-visibility red penetrant liquid for crack detection.",
    technicalCode: "YZN-NDT-001",
    material: "Kimyasal Çözücü",
    certification: "ISO 3452-2",
    price: 320,
    quantity: 500,
    inStock: true,
    specs: { hacim: "500ml", tip: "Tip II", hassasiyet: "Seviye 2" },
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 2,
    categoryId: "ndt",
    name: "Manyetik Parçacık Tozu - Siyah 1kg",
    name_tr: "Manyetik Parçacık Tozu - Siyah 1kg",
    name_en: "Magnetic Particle Powder - Black 1kg",
    description_tr: "Kuru yöntem manyetik parçacık muayenesi için yüksek kontrastlı toz.",
    description_en: "High-contrast powder for dry method magnetic particle inspection.",
    technicalCode: "YZN-NDT-002",
    material: "Demir Oksit",
    certification: "ASTM E1444",
    price: 450,
    quantity: 100,
    inStock: true,
    specs: { agirlik: "1kg", renk: "Siyah", sicaklik: "315°C" },
    image: "https://images.unsplash.com/photo-1530311701074-9ef4a446f62b?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 3,
    categoryId: "ndt",
    name: "Ultrasonik Muayene Jeli - 5 Litre",
    name_tr: "Ultrasonik Muayene Jeli - 5 Litre",
    name_en: "Ultrasonic Couplant Gel - 5L",
    description_tr: "Akustik iletimi maksimize eden, korozyon önleyici UT jeli.",
    description_en: "Anti-corrosive UT gel maximizing acoustic transmission.",
    technicalCode: "YZN-NDT-003",
    material: "Su Bazlı Polimer",
    certification: "ASTM E164",
    price: 280,
    quantity: 200,
    inStock: true,
    specs: { hacim: "5L", viskozite: "Yüksek", ph: "7.0" },
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 4,
    categoryId: "ndt",
    name: "UV-A LED El Lambası - Profesyonel",
    name_tr: "UV-A LED El Lambası - Profesyonel",
    name_en: "Professional UV-A LED Flashlight",
    description_tr: "Floresan penetrant ve manyetik parçacık testleri için 365nm UV lamba.",
    description_en: "365nm UV lamp for fluorescent penetrant and magnetic particle testing.",
    technicalCode: "YZN-NDT-004",
    material: "Alüminyum Gövde",
    certification: "CE / ISO 9001",
    price: 3250,
    quantity: 25,
    inStock: true,
    specs: { dalga_boyu: "365nm", guc: "10W", batarya: "Şarj Edilebilir" },
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 5,
    categoryId: "ndt",
    name: "Dijital Ultrasonik Kalınlık Ölçer",
    name_tr: "Dijital Ultrasonik Kalınlık Ölçer",
    name_en: "Digital Ultrasonic Thickness Gauge",
    description_tr: "Metal, plastik ve cam yüzeylerde hassas kalınlık ölçümü.",
    description_en: "Precision thickness measurement on metal, plastic, and glass surfaces.",
    technicalCode: "YZN-NDT-005",
    material: "Elektronik / ABS",
    certification: "EN 15317",
    price: 5800,
    quantity: 15,
    inStock: true,
    specs: { aralik: "1.0 - 300mm", hassasiyet: "0.01mm", ekran: "LCD" },
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 6,
    categoryId: "ndt",
    name: "Geliştirici Sprey (Developer) - Beyaz",
    name_tr: "Geliştirici Sprey (Developer) - Beyaz",
    name_en: "White Developer Spray",
    description_tr: "Penetrant sıvısını yüzeye çekerek çatlakları görünür kılan beyaz toz tabakası.",
    description_en: "White powder layer that draws penetrant to the surface to reveal cracks.",
    technicalCode: "YZN-NDT-006",
    material: "Solvent Bazlı",
    certification: "AMS 2644",
    price: 310,
    quantity: 450,
    inStock: true,
    specs: { hacim: "500ml", kuruma_hizi: "Hızlı", kalinti: "Düşük" },
    image: "https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 7,
    categoryId: "ndt",
    name: "Radyografik Film - Tip D7 10x40cm",
    name_tr: "Radyografik Film - Tip D7 10x40cm",
    name_en: "Radiographic Film - Type D7 10x40cm",
    description_tr: "Endüstriyel röntgen çekimleri için yüksek kontrastlı radyografik film.",
    description_en: "High-contrast radiographic film for industrial X-ray imaging.",
    technicalCode: "YZN-NDT-007",
    material: "Gümüş Halojenür",
    certification: "ISO 11699-1",
    price: 8400,
    quantity: 50,
    inStock: true,
    specs: { boyut: "10x40cm", paket: "100 Adet", sinif: "C5" },
    image: "https://images.unsplash.com/photo-1530210124550-912dc1381cb8?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 8,
    categoryId: "ndt",
    name: "Manyetik Yoke Cihazı - AC/DC",
    name_tr: "Manyetik Yoke Cihazı - AC/DC",
    name_en: "Magnetic Yoke - AC/DC",
    description_tr: "Yüzey çatlaklarını tespit etmek için taşınabilir elektromanyetik mıknatıs.",
    description_en: "Portable electromagnetic magnet for detecting surface cracks.",
    technicalCode: "YZN-NDT-008",
    material: "Çelik / Polimer",
    certification: "ASTM E709",
    price: 12500,
    quantity: 10,
    inStock: true,
    specs: { guc: "220V AC", kaldirma: "18kg (DC)", agirlik: "3.2kg" },
    image: "https://images.unsplash.com/photo-1581092162384-8987c1d64718?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 9,
    categoryId: "ndt",
    name: "Hassas Kumpas - 150mm Dijital",
    name_tr: "Hassas Kumpas - 150mm Dijital",
    name_en: "Precision Caliper - 150mm Digital",
    description_tr: "NDT öncesi ve sonrası parça boyut kontrolü için paslanmaz çelik kumpas.",
    description_en: "Stainless steel caliper for part size control before and after NDT.",
    technicalCode: "YZN-NDT-009",
    material: "Paslanmaz Çelik",
    certification: "DIN 862",
    price: 950,
    quantity: 60,
    inStock: true,
    specs: { aralik: "0-150mm", hassasiyet: "0.01mm", koruma: "IP54" },
    image: "https://images.unsplash.com/photo-1535813543266-73f83195c3e4?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 10,
    categoryId: "ndt",
    name: "V1 Kalibrasyon Bloğu - Karbon Çelik",
    name_tr: "V1 Kalibrasyon Bloğu - Karbon Çelik",
    name_en: "V1 Calibration Block - Carbon Steel",
    description_tr: "Ultrasonik test cihazlarının kalibrasyonu için standart referans bloğu.",
    description_en: "Standard reference block for calibration of ultrasonic testing equipment.",
    technicalCode: "YZN-NDT-010",
    material: "Karbon Çelik",
    certification: "EN ISO 2400",
    price: 2400,
    quantity: 20,
    inStock: true,
    specs: { tip: "V1 / IIW", malzeme: "S235JR", kaplama: "Nikel" },
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 11,
    categoryId: "ndt",
    name: "Eddy Current Yüzey Probu - 2MHz",
    name_tr: "Eddy Current Yüzey Probu - 2MHz",
    name_en: "Eddy Current Surface Probe - 2MHz",
    description_tr: "İletken malzemelerde yüzey altı çatlak tespiti için hassas prob.",
    description_en: "Precision probe for subsurface crack detection in conductive materials.",
    technicalCode: "YZN-NDT-011",
    material: "Seramik / Bakır",
    certification: "ISO 15549",
    price: 4800,
    quantity: 12,
    inStock: true,
    specs: { frekans: "2MHz", cap: "10mm", konnektör: "Microdot" },
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 12,
    categoryId: "ndt",
    name: "Lüksmetre - Dijital Işık Ölçer",
    name_tr: "Lüksmetre - Dijital Işık Ölçer",
    name_en: "Digital Lux Meter",
    description_tr: "Görsel muayene alanlarındaki ışık şiddetini ölçmek için dijital cihaz.",
    description_en: "Digital device to measure light intensity in visual inspection areas.",
    technicalCode: "YZN-NDT-012",
    material: "ABS Plastik",
    certification: "ISO 3059",
    price: 1150,
    quantity: 30,
    inStock: true,
    specs: { aralik: "0-200,000 Lux", hassasiyet: "%3", birim: "Lux / FC" },
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 13,
    categoryId: "ndt",
    name: "Sertlik Ölçüm Cihazı - Portatif Leeb",
    name_tr: "Sertlik Ölçüm Cihazı - Portatif Leeb",
    name_en: "Portable Leeb Hardness Tester",
    description_tr: "Ağır parçaların yerinde sertlik ölçümü için dijital darbe cihazı.",
    description_en: "Digital impact device for on-site hardness measurement of heavy parts.",
    technicalCode: "YZN-NDT-013",
    material: "Metal Alaşım",
    certification: "ASTM A956",
    price: 7200,
    quantity: 8,
    inStock: true,
    specs: { skalalar: "HRC, HRB, HB, HV", hafiza: "500 Grup", ekran: "OLED" },
    image: "https://images.unsplash.com/photo-1581092162384-8987c1d64718?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 14,
    categoryId: "ndt",
    name: "Vakum Kutusu - Kaynak Testi İçin",
    name_tr: "Vakum Kutusu - Kaynak Testi İçin",
    name_en: "Vacuum Box - For Weld Testing",
    description_tr: "Depolama tankı taban kaynaklarındaki sızıntı tespiti için vakum aparatı.",
    description_en: "Vacuum apparatus for leak detection in storage tank bottom welds.",
    technicalCode: "YZN-NDT-014",
    material: "Pleksiglas / Kauçuk",
    certification: "API 650",
    price: 8900,
    quantity: 5,
    inStock: true,
    specs: { boyut: "750mm", pompa: "Harici", conta: "Yumuşak Kauçuk" },
    image: "https://images.unsplash.com/photo-1535813543266-73f83195c3e4?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 15,
    categoryId: "ndt",
    name: "Sıcaklık Ölçer Tebeşir - 250°C",
    name_tr: "Sıcaklık Ölçer Tebeşir - 250°C",
    name_en: "Tempilstik Temperature Indicator - 250°C",
    description_tr: "Kaynak öncesi tavlama sıcaklığını kontrol etmek için eriyen tebeşir.",
    description_en: "Melting chalk to control preheat temperature before welding.",
    technicalCode: "YZN-NDT-015",
    material: "Termokromik Balmumu",
    certification: "NIST İzlenebilir",
    price: 185,
    quantity: 150,
    inStock: true,
    specs: { derece: "250°C", hassasiyet: "%1", paket: "Tekli" },
    image: "https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?q=80&w=800&auto=format&fit=crop"
  },

  // --- KAYNAK MALZEMELERİ (16-30) ---
  {
    id: 16,
    categoryId: "welding",
    name: "ER70S-6 Gazaltı Kaynak Teli 1.0mm 15kg",
    name_tr: "ER70S-6 Gazaltı Kaynak Teli 1.0mm 15kg",
    name_en: "ER70S-6 MIG Welding Wire 1.0mm 15kg",
    description_tr: "Genel imalat çelikleri için bakır kaplı yüksek kaliteli gazaltı teli.",
    description_en: "Copper-coated high-quality MIG wire for general fabrication steels.",
    technicalCode: "YZN-WELD-001",
    material: "Düşük Alaşımlı Çelik",
    certification: "AWS A5.18",
    price: 1850,
    quantity: 1000,
    inStock: true,
    specs: { cap: "1.0mm", agirlik: "15kg", makara: "Plastik/Hizli" },
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 17,
    categoryId: "welding",
    name: "E6013 Rutil Elektrod 3.25x350mm",
    name_tr: "E6013 Rutil Elektrod 3.25x350mm",
    name_en: "E6013 Rutile Electrode 3.25x350mm",
    description_tr: "Hafif çelik yapıların kaynağı için genel amaçlı rutil elektrod.",
    description_en: "General-purpose rutile electrode for welding mild steel structures.",
    technicalCode: "YZN-WELD-002",
    material: "Karbon Çelik",
    certification: "AWS A5.1",
    price: 420,
    quantity: 2000,
    inStock: true,
    specs: { boyut: "3.25x350mm", kutu: "5kg", akim: "90-130A" },
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 18,
    categoryId: "welding",
    name: "Paslanmaz TIG Teli 308L 2.4mm 5kg",
    name_tr: "Paslanmaz TIG Teli 308L 2.4mm 5kg",
    name_en: "Stainless TIG Wire 308L 2.4mm 5kg",
    description_tr: "304 ve 304L paslanmaz çeliklerin TIG kaynağı için dolgu teli.",
    description_en: "Filler wire for TIG welding of 304 and 304L stainless steels.",
    technicalCode: "YZN-WELD-003",
    material: "308L Paslanmaz Çelik",
    certification: "AWS A5.9",
    price: 2450,
    quantity: 300,
    inStock: true,
    specs: { cap: "2.4mm", uzunluk: "1000mm", paket: "5kg" },
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 19,
    categoryId: "welding",
    name: "Otomatik Kararan Kaynak Maskesi - 9-13 DIN",
    name_tr: "Otomatik Kararan Kaynak Maskesi - 9-13 DIN",
    name_en: "Auto-Darkening Welding Helmet - 9-13 DIN",
    description_tr: "Göz sağlığını koruyan, hızlı kararma özellikli profesyonel kaynak maskesi.",
    description_en: "Professional welding helmet with fast darkening to protect eye health.",
    technicalCode: "YZN-WELD-004",
    material: "Yüksek Darbe Polimer",
    certification: "ANSI Z87.1 / EN 379",
    price: 2150,
    quantity: 80,
    inStock: true,
    specs: { sensor: "4 Adet", guc: "Güneş Pili + Pil", hizi: "1/25,000s" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 20,
    categoryId: "welding",
    name: "Argon Gaz Regülatörü - Pirinç Gövde",
    name_tr: "Argon Gaz Regülatörü - Pirinç Gövde",
    name_en: "Argon Gas Regulator - Brass Body",
    description_tr: "TIG ve MIG kaynaklarında hassas gaz debi kontrolü sağlayan regülatör.",
    description_en: "Regulator providing precise gas flow control in TIG and MIG welding.",
    technicalCode: "YZN-WELD-005",
    material: "Dövme Pirinç",
    certification: "EN ISO 2503",
    price: 1350,
    quantity: 120,
    inStock: true,
    specs: { giris: "230 Bar", cikis: "0-32 L/dk", baglanti: "W21.8 x 1/14" },
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 21,
    categoryId: "welding",
    name: "Kaynak Battaniyesi - 2x2m Yanmaz Silis",
    name_tr: "Kaynak Battaniyesi - 2x2m Yanmaz Silis",
    name_en: "Welding Blanket - 2x2m Fireproof Silica",
    description_tr: "Çalışma alanını kaynak sıçrantılarından koruyan yüksek sıcaklık battaniyesi.",
    description_en: "High-temperature blanket protecting work area from welding spatters.",
    technicalCode: "YZN-WELD-006",
    material: "Silika Kumaş",
    certification: "EN 13501-1",
    price: 2850,
    quantity: 45,
    inStock: true,
    specs: { boyut: "2x2m", sicaklik: "1000°C Sürekli", kalınlık: "0.7mm" },
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 22,
    categoryId: "welding",
    name: "TIG Kaynak Torcu - 4m Hava Soğutmalı",
    name_tr: "TIG Kaynak Torcu - 4m Hava Soğutmalı",
    name_en: "TIG Welding Torch - 4m Air Cooled",
    description_tr: "Esnek kablo yapısına sahip, ergonomik TIG kaynak torcu.",
    description_en: "Ergonomic TIG welding torch with flexible cable structure.",
    technicalCode: "YZN-WELD-007",
    material: "Bakır / Kauçuk",
    certification: "IEC 60974-7",
    price: 3400,
    quantity: 35,
    inStock: true,
    specs: { uzunluk: "4m", akim: "200A DC", tip: "WP-26" },
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 23,
    categoryId: "welding",
    name: "Kaynakçı Pensesi - 500A Profesyonel",
    name_tr: "Kaynakçı Pensesi - 500A Profesyonel",
    name_en: "Electrode Holder - 500A Professional",
    description_tr: "Elektrot kaynağı için yüksek iletkenlikli, ısınmayan pense.",
    description_en: "High-conductivity, non-heating holder for electrode welding.",
    technicalCode: "YZN-WELD-008",
    material: "Pirinç / Fiberglas",
    certification: "EN 60974-11",
    price: 480,
    quantity: 150,
    inStock: true,
    specs: { kapasite: "500A", kablo: "50-95mm2", yay: "Güçlendirilmiş" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 24,
    categoryId: "welding",
    name: "Kaynak Sıçrantı Önleyici Sprey - 400ml",
    name_tr: "Kaynak Sıçrantı Önleyici Sprey - 400ml",
    name_en: "Anti-Spatter Spray - 400ml",
    description_tr: "Sıçrantıların metale yapışmasını engelleyen silikonsuz sprey.",
    description_en: "Silicone-free spray preventing spatters from adhering to metal.",
    technicalCode: "YZN-WELD-009",
    material: "Su Bazlı",
    certification: "REACH Uyumlu",
    price: 145,
    quantity: 600,
    inStock: true,
    specs: { hacim: "400ml", silikon: "Yok", boyanabilir: "Evet" },
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 25,
    categoryId: "welding",
    name: "Manyetik Kaynak Gönyesi - 22kg",
    name_tr: "Manyetik Kaynak Gönyesi - 22kg",
    name_en: "Magnetic Welding Square - 22kg",
    description_tr: "Parçaları kaynak öncesi 45, 90 ve 135 derecelerde sabit tutan mıknatıs.",
    description_en: "Magnet holding parts at 45, 90, and 135 degrees before welding.",
    technicalCode: "YZN-WELD-010",
    material: "Ferrit Mıknatıs / Çelik",
    certification: "CE",
    price: 320,
    quantity: 250,
    inStock: true,
    specs: { guc: "22kg", acilar: "45°, 90°, 135°", boyut: "Büyük" },
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 26,
    categoryId: "welding",
    name: "Alüminyum Kaynak Teli 5356 1.2mm 7kg",
    name_tr: "Alüminyum Kaynak Teli 5356 1.2mm 7kg",
    name_en: "Aluminum Welding Wire 5356 1.2mm 7kg",
    description_tr: "Denizcilik ve yapısal uygulamalar için yüksek dayanımlı alüminyum teli.",
    description_en: "High-strength aluminum wire for marine and structural applications.",
    technicalCode: "YZN-WELD-011",
    material: "AlMg5 Alaşımı",
    certification: "AWS A5.10",
    price: 3100,
    quantity: 180,
    inStock: true,
    specs: { cap: "1.2mm", agirlik: "7kg", makara: "S300" },
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 27,
    categoryId: "welding",
    name: "Seramik Kaynak Altlığı - 12mm Düz",
    name_tr: "Seramik Kaynak Altlığı - 12mm Düz",
    name_en: "Ceramic Welding Backing - 12mm Flat",
    description_tr: "Tek taraflı kaynaklarda kök pasosu kalitesini artıran seramik altlık.",
    description_en: "Ceramic backing improving root pass quality in single-sided welding.",
    technicalCode: "YZN-WELD-012",
    material: "Kordiyerit Seramik",
    certification: "ISO 9001",
    price: 85,
    quantity: 1200,
    inStock: true,
    specs: { genislik: "12mm", uzunluk: "600mm", bant: "Alüminyum" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 28,
    categoryId: "welding",
    name: "Wolfram Elektrod - %2 Lantanyumlu (Mavi)",
    name_tr: "Wolfram Elektrod - %2 Lantanyumlu (Mavi)",
    name_en: "Tungsten Electrode - 2% Lanthanated (Blue)",
    description_tr: "TIG kaynağı için uzun ömürlü, radyoaktif olmayan wolfram elektrod.",
    description_en: "Long-lasting, non-radioactive tungsten electrode for TIG welding.",
    technicalCode: "YZN-WELD-013",
    material: "Wolfram + %2 La2O3",
    certification: "ISO 6848",
    price: 1150,
    quantity: 500,
    inStock: true,
    specs: { cap: "2.4mm", uzunluk: "175mm", paket: "10 Adet" },
    image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 29,
    categoryId: "welding",
    name: "Kaynak Kablosu - 50mm2 Saf Bakır",
    name_tr: "Kaynak Kablosu - 50mm2 Saf Bakır",
    name_en: "Welding Cable - 50mm2 Pure Copper",
    description_tr: "Yüksek akım taşıma kapasiteli, esnek kauçuk kaplı kaynak kablosu.",
    description_en: "Flexible rubber-coated welding cable with high current carrying capacity.",
    technicalCode: "YZN-WELD-014",
    material: "Elektrolitik Bakır",
    certification: "H01N2-D",
    price: 450,
    quantity: 1000,
    inStock: true,
    specs: { kesit: "50mm2", kaplama: "Neopren", birim: "Metre" },
    image: "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 30,
    categoryId: "welding",
    name: "Gazaltı Kaynak Nozulu - Konik Tip",
    name_tr: "Gazaltı Kaynak Nozulu - Konik Tip",
    name_en: "MIG Welding Nozzle - Conical Type",
    description_tr: "MIG/MAG torçları için gaz akışını yönlendiren bakır nozul.",
    description_en: "Copper nozzle directing gas flow for MIG/MAG torches.",
    technicalCode: "YZN-WELD-015",
    material: "Bakır Alaşımı",
    certification: "OEM Uyumlu",
    price: 120,
    quantity: 400,
    inStock: true,
    specs: { tip: "Konik", uyum: "Binzel MB25", adet: "5'li Paket" },
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop"
  },

  // --- YAPI KİMYASALLARI (31-45) ---
  {
    id: 31,
    categoryId: "construction",
    name: "Epoksi Ankraj Harcı - 300ml Kartuş",
    name_tr: "Epoksi Ankraj Harcı - 300ml Kartuş",
    name_en: "Epoxy Anchor Mortar - 300ml Cartridge",
    description_tr: "Beton ve duvarlarda ağır yük ankrajları için yüksek performanslı epoksi harç.",
    description_en: "High-performance epoxy mortar for heavy-duty anchoring in concrete and masonry.",
    technicalCode: "YZN-CONS-001",
    material: "Vinilester Reçine",
    certification: "ETA-17/0284",
    price: 480,
    quantity: 700,
    inStock: true,
    specs: { hacim: "300ml", kuruma_suresi: "30dk (20°C)", uygulama: "Tabanca" },
    image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 32,
    categoryId: "construction",
    name: "Poliüretan Mastik - Gri 600ml Sosis",
    name_tr: "Poliüretan Mastik - Gri 600ml Sosis",
    name_en: "Polyurethane Sealant - Grey 600ml Sausage",
    description_tr: "İnşaat derzleri için yüksek elastikiyetli, UV dayanımlı poliüretan mastik.",
    description_en: "High-elasticity, UV-resistant polyurethane sealant for construction joints.",
    technicalCode: "YZN-CONS-002",
    material: "Poliüretan",
    certification: "ISO 11600 F 25 LM",
    price: 210,
    quantity: 1500,
    inStock: true,
    specs: { hacim: "600ml", renk: "Gri", hareket_kapasitesi: "%25" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 33,
    categoryId: "construction",
    name: "Tamir Harcı - Hızlı Priz Alan 25kg",
    name_tr: "Tamir Harcı - Hızlı Priz Alan 25kg",
    name_en: "Rapid Setting Repair Mortar - 25kg",
    description_tr: "Beton ve şap tamirleri için yüksek mukavemetli, hızlı priz alan harç.",
    description_en: "High-strength, rapid-setting mortar for concrete and screed repairs.",
    technicalCode: "YZN-CONS-003",
    material: "Çimento Esaslı",
    certification: "EN 1504-3 R3",
    price: 380,
    quantity: 800,
    inStock: true,
    specs: { agirlik: "25kg", priz_suresi: "15-20dk", basinç_dayanimi: "30 N/mm²" },
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 34,
    categoryId: "construction",
    name: "Su Yalıtım Membranı - Likit Bitüm Esaslı 20kg",
    name_tr: "Su Yalıtım Membranı - Likit Bitüm Esaslı 20kg",
    name_en: "Liquid Bitumen Waterproofing Membrane - 20kg",
    description_tr: "Temel, çatı ve ıslak hacimlerde kullanılan esnek likit su yalıtım membranı.",
    description_en: "Flexible liquid waterproofing membrane for foundations, roofs, and wet areas.",
    technicalCode: "YZN-CONS-004",
    material: "Bitüm Kauçuk",
    certification: "TS EN 15814",
    price: 950,
    quantity: 300,
    inStock: true,
    specs: { agirlik: "20kg", uygulama: "Fırça/Rulo", kuruma: "24 saat" },
    image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 35,
    categoryId: "construction",
    name: "Epoksi Zemin Kaplama - Şeffaf 10kg Set",
    name_tr: "Epoksi Zemin Kaplama - Şeffaf 10kg Set",
    name_en: "Epoxy Floor Coating - Clear 10kg Set",
    description_tr: "Endüstriyel zeminler için kimyasal ve aşınma dayanımlı şeffaf epoksi kaplama.",
    description_en: "Chemical and abrasion resistant clear epoxy coating for industrial floors.",
    technicalCode: "YZN-CONS-005",
    material: "Epoksi Reçine + Sertleştirici",
    certification: "EN 13813",
    price: 2800,
    quantity: 150,
    inStock: true,
    specs: { agirlik: "10kg (A+B)", katı_oranı: "%100", parlaklik: "Yüksek" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 36,
    categoryId: "construction",
    name: "Çimento Esaslı Seramik Yapıştırıcı - C2TE S1 25kg",
    name_tr: "Çimento Esaslı Seramik Yapıştırıcı - C2TE S1 25kg",
    name_en: "Cement-Based Tile Adhesive - C2TE S1 25kg",
    description_tr: "İç ve dış mekanlarda esnek, yüksek performanslı seramik yapıştırıcı.",
    description_en: "Flexible, high-performance tile adhesive for indoor and outdoor use.",
    technicalCode: "YZN-CONS-006",
    material: "Çimento / Polimer",
    certification: "EN 12004",
    price: 180,
    quantity: 2000,
    inStock: true,
    specs: { agirlik: "25kg", kayma: "Azaltılmış", esneklik: "S1" },
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 37,
    categoryId: "construction",
    name: "Beton Kür Malzemesi - Akrilik Esaslı 20L",
    name_tr: "Beton Kür Malzemesi - Akrilik Esaslı 20L",
    name_en: "Concrete Curing Compound - Acrylic Based 20L",
    description_tr: "Yeni dökülmüş betonun hızlı su kaybını önleyen akrilik esaslı kür malzemesi.",
    description_en: "Acrylic-based curing compound preventing rapid water loss in fresh concrete.",
    technicalCode: "YZN-CONS-007",
    material: "Akrilik Reçine",
    certification: "ASTM C309",
    price: 720,
    quantity: 180,
    inStock: true,
    specs: { hacim: "20L", uygulama: "Püskürtme", verim: "5-7 m²/L" },
    image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 38,
    categoryId: "construction",
    name: "Poliüretan Enjeksiyon Reçinesi - Su Kesici",
    name_tr: "Poliüretan Enjeksiyon Reçinesi - Su Kesici",
    name_en: "Polyurethane Injection Resin - Water Stopper",
    description_tr: "Beton çatlaklarından gelen su sızıntılarını durduran hızlı reaksiyonlu reçine.",
    description_en: "Fast-reacting resin stopping water leaks from concrete cracks.",
    technicalCode: "YZN-CONS-008",
    material: "Hidrofilik Poliüretan",
    certification: "CE",
    price: 1800,
    quantity: 90,
    inStock: true,
    specs: { hacim: "10kg", genlesme: "10-20 Kat", uygulama: "Enjeksiyon" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 39,
    categoryId: "construction",
    name: "Derz Dolgu Harcı - Epoksi Esaslı 5kg",
    name_tr: "Derz Dolgu Harcı - Epoksi Esaslı 5kg",
    name_en: "Epoxy Grout - 5kg",
    description_tr: "Kimyasal dayanımlı, hijyenik ve kolay temizlenebilir epoksi derz dolgu.",
    description_en: "Chemical-resistant, hygienic, and easy-to-clean epoxy grout.",
    technicalCode: "YZN-CONS-009",
    material: "Epoksi Reçine",
    certification: "EN 13888 RG",
    price: 750,
    quantity: 250,
    inStock: true,
    specs: { agirlik: "5kg (A+B)", renk: "Çeşitli", kullanim: "Endüstriyel" },
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 40,
    categoryId: "construction",
    name: "Yapısal Güçlendirme Karbon Elyaf Kumaş 300gr/m²",
    name_tr: "Yapısal Güçlendirme Karbon Elyaf Kumaş 300gr/m²",
    name_en: "Structural Reinforcement Carbon Fiber Fabric 300gsm",
    description_tr: "Betonarme yapıların güçlendirilmesi için yüksek mukavemetli karbon elyaf.",
    description_en: "High-strength carbon fiber for reinforcement of concrete structures.",
    technicalCode: "YZN-CONS-010",
    material: "Karbon Elyaf",
    certification: "ASTM D3039",
    price: 4500,
    quantity: 50,
    inStock: true,
    specs: { agirlik: "300gr/m²", genislik: "50cm", rulo: "50m" },
    image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 41,
    categoryId: "construction",
    name: "Şap Katkısı - Akışkanlaştırıcı 20kg",
    name_tr: "Şap Katkısı - Akışkanlaştırıcı 20kg",
    name_en: "Screed Additive - Plasticizer 20kg",
    description_tr: "Çimento esaslı şapların işlenebilirliğini ve mukavemetini artıran katkı.",
    description_en: "Additive improving workability and strength of cement-based screeds.",
    technicalCode: "YZN-CONS-011",
    material: "Polikarboksilat Esaslı",
    certification: "EN 934-2",
    price: 620,
    quantity: 200,
    inStock: true,
    specs: { agirlik: "20kg", dozaj: "%0.5 - %1.5", etki: "Akışkanlaştırıcı" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 42,
    categoryId: "construction",
    name: "Kalıp Ayırıcı Yağ - Su Bazlı 20L",
    name_tr: "Kalıp Ayırıcı Yağ - Su Bazlı 20L",
    name_en: "Formwork Release Agent - Water Based 20L",
    description_tr: "Beton kalıplarının kolay ayrılmasını sağlayan çevre dostu ayırıcı yağ.",
    description_en: "Environmentally friendly release agent for easy demolding of concrete forms.",
    technicalCode: "YZN-CONS-012",
    material: "Mineral Yağ Emülsiyonu",
    certification: "DIN 18217",
    price: 890,
    quantity: 100,
    inStock: true,
    specs: { hacim: "20L", baz: "Su", uygulama: "Püskürtme" },
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 43,
    categoryId: "construction",
    name: "Hızlı Montaj Köpüğü - Tabancalı 750ml",
    name_tr: "Hızlı Montaj Köpüğü - Tabancalı 750ml",
    name_en: "Rapid Mounting Foam - Gun Grade 750ml",
    description_tr: "Kapı, pencere kasası montajı ve boşluk doldurma için tek komponentli köpük.",
    description_en: "Single-component foam for door, window frame installation and gap filling.",
    technicalCode: "YZN-CONS-013",
    material: "Poliüretan",
    certification: "EN 13501-1",
    price: 160,
    quantity: 1000,
    inStock: true,
    specs: { hacim: "750ml", genlesme: "40 Litre", kuruma: "15dk" },
    image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 44,
    categoryId: "construction",
    name: "Akrilik Mastik - Beyaz 310ml Kartuş",
    name_tr: "Akrilik Mastik - Beyaz 310ml Kartuş",
    name_en: "Acrylic Sealant - White 310ml Cartridge",
    description_tr: "İç mekanlarda çatlak ve derz dolgusu için boyanabilir akrilik mastik.",
    description_en: "Paintable acrylic sealant for cracks and joints in interior applications.",
    technicalCode: "YZN-CONS-014",
    material: "Akrilik Polimer",
    certification: "EN 15651-1",
    price: 85,
    quantity: 2500,
    inStock: true,
    specs: { hacim: "310ml", renk: "Beyaz", esneklik: "Orta" },
    image: "https://images.unsplash.com/photo-1516216628859-9bccecab13ca?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 45,
    categoryId: "construction",
    name: "Beton Yüzey Sertleştirici - Toz 25kg",
    name_tr: "Beton Yüzey Sertleştirici - Toz 25kg",
    name_en: "Concrete Surface Hardener - Powder 25kg",
    description_tr: "Endüstriyel zeminlerde aşınma direncini artıran çimento esaslı toz.",
    description_en: "Cement-based powder increasing abrasion resistance on industrial floors.",
    technicalCode: "YZN-CONS-015",
    material: "Çimento / Agrega",
    certification: "EN 13813",
    price: 420,
    quantity: 600,
    inStock: true,
    specs: { agirlik: "25kg", uygulama: "Serpme", renk: "Gri" },
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop"
  },

  // --- YÜZEY İŞLEM (46-60) ---
  {
    id: 46,
    categoryId: "surface",
    name: "Grit G50 Kumlama Kumu 25kg",
    name_tr: "Grit G50 Kumlama Kumu 25kg",
    name_en: "Grit G50 Blasting Abrasive 25kg",
    description_tr: "Orta seviye pas ve boya sökümü için köşeli çelik grit.",
    description_en: "Angular steel grit for medium level rust and paint removal.",
    technicalCode: "YZN-SURF-016",
    material: "Çelik Grit",
    certification: "ISO 11124",
    price: 1180,
    quantity: 1800,
    inStock: true,
    specs: { boyut: "0.3 - 0.8mm", sertlik: "60-66 HRC", agirlik: "25kg" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 47,
    categoryId: "surface",
    name: "Seramik Kumlama Kumu - Beyaz 25kg",
    name_tr: "Seramik Kumlama Kumu - Beyaz 25kg",
    name_en: "Ceramic Blasting Media - White 25kg",
    description_tr: "Paslanmaz çelik ve alüminyum için demir içermeyen, tekrar kullanılabilir kum.",
    description_en: "Iron-free, reusable blasting media for stainless steel and aluminum.",
    technicalCode: "YZN-SURF-017",
    material: "Zirkonyum Oksit",
    certification: "FEPA F",
    price: 2800,
    quantity: 400,
    inStock: true,
    specs: { boyut: "200-400 mic", sertlik: "7 Mohs", agirlik: "25kg" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 48,
    categoryId: "surface",
    name: "Paslanmaz Çelik Tel Fırça - Dairesel 100mm",
    name_tr: "Paslanmaz Çelik Tel Fırça - Dairesel 100mm",
    name_en: "Stainless Steel Wire Brush - Circular 100mm",
    description_tr: "Paslanmaz yüzeylerde pas ve boya temizliği için dairesel tel fırça.",
    description_en: "Circular wire brush for rust and paint removal on stainless surfaces.",
    technicalCode: "YZN-SURF-018",
    material: "Paslanmaz Çelik Tel",
    certification: "DIN EN 1083-1",
    price: 210,
    quantity: 900,
    inStock: true,
    specs: { cap: "100mm", tel_kalinligi: "0.3mm", baglanti: "M14" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 49,
    categoryId: "surface",
    name: "Elmas Taşlama Diski - Beton 125mm",
    name_tr: "Elmas Taşlama Diski - Beton 125mm",
    name_en: "Diamond Grinding Disc - Concrete 125mm",
    description_tr: "Beton, şap ve doğal taş yüzeylerin taşlanması için elmas disk.",
    description_en: "Diamond disc for grinding concrete, screed, and natural stone surfaces.",
    technicalCode: "YZN-SURF-019",
    material: "Elmas Segmentli Çelik",
    certification: "EN 13236",
    price: 780,
    quantity: 300,
    inStock: true,
    specs: { cap: "125mm", segment_sayisi: "18", kullanim: "Kuru/Islak" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 50,
    categoryId: "surface",
    name: "Boya Sökücü Jel - Endüstriyel 5kg",
    name_tr: "Boya Sökücü Jel - Endüstriyel 5kg",
    name_en: "Paint Stripper Gel - Industrial 5kg",
    description_tr: "Metal yüzeylerdeki eski boya ve kaplamaları etkili bir şekilde söken jel.",
    description_en: "Gel effectively removing old paint and coatings from metal surfaces.",
    technicalCode: "YZN-SURF-020",
    material: "Solvent Bazlı",
    certification: "MSDS Mevcut",
    price: 620,
    quantity: 250,
    inStock: true,
    specs: { agirlik: "5kg", uygulama: "Fırça", etki: "15-60 dk" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 51,
    categoryId: "surface",
    name: "Aşındırıcı Ped - Yüzey Hazırlık (SCM) 125mm",
    name_tr: "Aşındırıcı Ped - Yüzey Hazırlık (SCM) 125mm",
    name_en: "Abrasive Pad - Surface Conditioning (SCM) 125mm",
    description_tr: "Kaynak temizliği, çapak alma ve yüzey hazırlığı için dokumasız ped.",
    description_en: "Non-woven pad for weld cleaning, deburring, and surface preparation.",
    technicalCode: "YZN-SURF-021",
    material: "Silikon Karbür / Naylon",
    certification: "ISO 9001",
    price: 75,
    quantity: 1500,
    inStock: true,
    specs: { cap: "125mm", kum: "Coarse/Medium/Fine", baglanti: "Cırt Cırt" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 52,
    categoryId: "surface",
    name: "Kumlama Hortumu - 19mm İç Çap",
    name_tr: "Kumlama Hortumu - 19mm İç Çap",
    name_en: "Blasting Hose - 19mm Inner Diameter",
    description_tr: "Aşındırıcı kumlama makineleri için yüksek aşınma dayanımlı hortum.",
    description_en: "High abrasion resistant hose for abrasive blasting machines.",
    technicalCode: "YZN-SURF-022",
    material: "Doğal Kauçuk / SBR",
    certification: "ISO 3861",
    price: 380,
    quantity: 500,
    inStock: true,
    specs: { ic_cap: "19mm", dis_cap: "33mm", basinç: "12 Bar" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 53,
    categoryId: "surface",
    name: "Pasivasyon Pastası - Paslanmaz Çelik 1kg",
    name_tr: "Pasivasyon Pastası - Paslanmaz Çelik 1kg",
    name_en: "Passivation Paste - Stainless Steel 1kg",
    description_tr: "Paslanmaz çelik kaynak dikişlerinde pasivasyon ve temizlik için pasta.",
    description_en: "Paste for passivation and cleaning of stainless steel weld seams.",
    technicalCode: "YZN-SURF-023",
    material: "Nitrik Asit Bazlı",
    certification: "ASTM A380",
    price: 980,
    quantity: 180,
    inStock: true,
    specs: { agirlik: "1kg", uygulama: "Fırça", etki: "15-60 dk" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 54,
    categoryId: "surface",
    name: "Manyetik Parçacık Test Cihazı - Portatif",
    name_tr: "Manyetik Parçacık Test Cihazı - Portatif",
    name_en: "Magnetic Particle Testing Device - Portable",
    description_tr: "Küçük ve orta boyutlu parçaların manyetik parçacık muayenesi için portatif cihaz.",
    description_en: "Portable device for magnetic particle inspection of small to medium parts.",
    technicalCode: "YZN-SURF-024",
    material: "Metal / Elektronik",
    certification: "ASTM E709",
    price: 15000,
    quantity: 8,
    inStock: true,
    specs: { guc: "220V AC", akim: "0-1500A", agirlik: "15kg" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 55,
    categoryId: "surface",
    name: "Boya Tabancası - Hava Destekli HVLP",
    name_tr: "Boya Tabancası - Hava Destekli HVLP",
    name_en: "Spray Gun - Air Assisted HVLP",
    description_tr: "Endüstriyel boya uygulamaları için yüksek transfer verimli HVLP tabanca.",
    description_en: "High transfer efficiency HVLP gun for industrial paint applications.",
    technicalCode: "YZN-SURF-025",
    material: "Alüminyum / Paslanmaz Çelik",
    certification: "CE",
    price: 2800,
    quantity: 60,
    inStock: true,
    specs: { meme_cap: "1.4mm", hava_basinci: "2 Bar", hazne: "600ml" },
    image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 56,
    categoryId: "surface",
    name: "Kumlama Kabini - Endüstriyel Tip",
    name_tr: "Kumlama Kabini - Endüstriyel Tip",
    name_en: "Blasting Cabinet - Industrial Type",
    description_tr: "Küçük ve orta boyutlu parçaların kapalı ortamda kumlanması için kabin.",
    description_en: "Cabinet for blasting small to medium parts in a closed environment.",
    technicalCode: "YZN-SURF-026",
    material: "Çelik Sac",
    certification: "CE",
    price: 22000,
    quantity: 5,
    inStock: true,
    specs: { ic_hacim: "800x600x600mm", aydinlatma: "LED", toz_toplama: "Entegre" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 57,
    categoryId: "surface",
    name: "Yüzey Temizleme Mendili - Endüstriyel",
    name_tr: "Yüzey Temizleme Mendili - Endüstriyel",
    name_en: "Surface Cleaning Wipe - Industrial",
    description_tr: "Yağ, gres ve kirleri temizlemek için endüstriyel tip, tüy bırakmayan mendil.",
    description_en: "Industrial-grade, lint-free wipe for cleaning oil, grease, and dirt.",
    technicalCode: "YZN-SURF-027",
    material: "Selüloz / Polipropilen",
    certification: "ISO 9001",
    price: 180,
    quantity: 2000,
    inStock: true,
    specs: { boyut: "30x30cm", paket: "200 Adet", kullanim: "Çok Amaçlı" },
    image: "https://images.unsplash.com/photo-1513467655676-561b3d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 58,
    categoryId: "surface",
    name: "Manyetik Kalınlık Ölçer - Boya/Kaplama",
    name_tr: "Manyetik Kalınlık Ölçer - Boya/Kaplama",
    name_en: "Magnetic Coating Thickness Gauge",
    description_tr: "Demir metaller üzerindeki manyetik olmayan kaplamaların kalınlığını ölçer.",
    description_en: "Measures thickness of non-magnetic coatings on ferrous metals.",
    technicalCode: "YZN-SURF-028",
    material: "Metal / Elektronik",
    certification: "ISO 2178",
    price: 1800,
    quantity: 50,
    inStock: true,
    specs: { aralik: "0-1500 um", hassasiyet: "%3", prob: "Entegre" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 59,
    categoryId: "surface",
    name: "Zımpara Makinesi - Orbital Havalı 150mm",
    name_tr: "Zımpara Makinesi - Orbital Havalı 150mm",
    name_en: "Orbital Air Sander - 150mm",
    description_tr: "Ahşap, metal ve kompozit yüzeylerde hassas zımparalama için havalı makine.",
    description_en: "Air-powered machine for precision sanding on wood, metal, and composite surfaces.",
    technicalCode: "YZN-SURF-029",
    material: "Alüminyum / Kompozit",
    certification: "CE",
    price: 3200,
    quantity: 30,
    inStock: true,
    specs: { taban_cap: "150mm", devir: "10,000 rpm", hava_tuketimi: "400 L/dk" },
    image: "https://images.unsplash.com/photo-1513467655676-561b3d489a88?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 60,
    categoryId: "surface",
    name: "Sulu Kumlama Adaptörü - Yüksek Basınçlı Yıkama İçin",
    name_tr: "Sulu Kumlama Adaptörü - Yüksek Basınçlı Yıkama İçin",
    name_en: "Wet Blasting Adapter - For Pressure Washer",
    description_tr: "Yüksek basınçlı yıkama makinelerini sulu kumlama sistemine dönüştüren adaptör.",
    description_en: "Adapter converting pressure washers into wet blasting systems.",
    technicalCode: "YZN-SURF-030",
    material: "Paslanmaz Çelik / Seramik",
    certification: "ISO 9001",
    price: 1200,
    quantity: 70,
    inStock: true,
    specs: { basinç: "200 Bar", meme: "Seramik", hortum: "3m" },
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=800&auto=format&fit=crop"
  },

  // --- İŞ GÜVENLİĞİ (61-75) ---
  {
    id: 61,
    categoryId: "safety",
    name: "Kimyasal Dayanıklı Eldiven - Nitril 33cm",
    name_tr: "Kimyasal Dayanıklı Eldiven - Nitril 33cm",
    name_en: "Chemical Resistant Glove - Nitrile 33cm",
    description_tr: "Asit, baz ve solventlere karşı koruma sağlayan uzun konçlu nitril eldiven.",
    description_en: "Long-cuff nitrile glove providing protection against acids, bases, and solvents.",
    technicalCode: "YZN-SAFE-016",
    material: "Nitril Kauçuk",
    certification: "EN 374",
    price: 95,
    quantity: 1800,
    inStock: true,
    specs: { uzunluk: "33cm", kalinlik: "0.38mm", beden: "7-11" },
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 62,
    categoryId: "safety",
    name: "Tam Yüz Gaz Maskesi - Panoramik Vizör",
    name_tr: "Tam Yüz Gaz Maskesi - Panoramik Vizör",
    name_en: "Full Face Gas Mask - Panoramic Visor",
    description_tr: "Geniş görüş açılı vizöre sahip, kimyasal ve gazlara karşı tam yüz koruması.",
    description_en: "Full face protection against chemicals and gases with wide-angle visor.",
    technicalCode: "YZN-SAFE-017",
    material: "Silikon / Polikarbonat",
    certification: "EN 136",
    price: 2100,
    quantity: 100,
    inStock: true,
    specs: { filtre_tipi: "Vida Bağlantılı", vizör: "Anti-Sis", agirlik: "550g" },
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 63,
    categoryId: "safety",
    name: "Kaynakçı Gözlüğü - Otomatik Kararan",
    name_tr: "Kaynakçı Gözlüğü - Otomatik Kararan",
    name_en: "Auto-Darkening Welding Goggles",
    description_tr: "Hafif ve kompakt yapıda, otomatik kararan kaynakçı gözlüğü.",
    description_en: "Lightweight and compact auto-darkening welding goggles.",
    technicalCode: "YZN-SAFE-018",
    material: "Polikarbonat",
    certification: "EN 379",
    price: 750,
    quantity: 300,
    inStock: true,
    specs: { kararma_araligi: "9-13 DIN", tepki_suresi: "1/5000s", uv_koruma: "%100" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 64,
    categoryId: "safety",
    name: "İş Güvenliği Ayakkabısı - Kompozit Burunlu S1P",
    name_tr: "İş Güvenliği Ayakkabısı - Kompozit Burunlu S1P",
    name_en: "Safety Shoe - Composite Toe S1P",
    description_tr: "Hafif, metal içermeyen kompozit burunlu ve delinmeye dayanıklı iş ayakkabısı.",
    description_en: "Lightweight, metal-free composite toe and puncture-resistant safety shoe.",
    technicalCode: "YZN-SAFE-019",
    material: "Süet Deri / Kompozit",
    certification: "EN ISO 20345:2011",
    price: 1100,
    quantity: 700,
    inStock: true,
    specs: { beden: "36-47", koruma: "S1P", taban: "Kaymaz PU" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 65,
    categoryId: "safety",
    name: "Kulak Tıkacı - Tekrar Kullanılabilir Silikon",
    name_tr: "Kulak Tıkacı - Tekrar Kullanılabilir Silikon",
    name_en: "Reusable Silicone Earplugs",
    description_tr: "Yüksek gürültülü ortamlar için konforlu, yıkanabilir kulak tıkacı.",
    description_en: "Comfortable, washable earplugs for high-noise environments.",
    technicalCode: "YZN-SAFE-020",
    material: "Silikon",
    certification: "EN 352-2",
    price: 45,
    quantity: 3000,
    inStock: true,
    specs: { snr: "28dB", paket: "Kutu + İp", kullanim: "Çoklu" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 66,
    categoryId: "safety",
    name: "Endüstriyel Emniyet Bareti - Entegre Vizörlü",
    name_tr: "Endüstriyel Emniyet Bareti - Entegre Vizörlü",
    name_en: "Industrial Safety Helmet - Integrated Visor",
    description_tr: "Darbe ve sıçramalara karşı entegre vizörlü, ayarlanabilir endüstriyel baret.",
    description_en: "Adjustable industrial helmet with integrated visor against impact and splashes.",
    technicalCode: "YZN-SAFE-021",
    material: "ABS",
    certification: "EN 397 / EN 166",
    price: 720,
    quantity: 200,
    inStock: true,
    specs: { renk: "Sarı/Mavi", vizör: "Polikarbonat", havalandirma: "Var" },
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 67,
    categoryId: "safety",
    name: "Düşme Durdurucu Şok Emicili Lanyard - 2m",
    name_tr: "Düşme Durdurucu Şok Emicili Lanyard - 2m",
    name_en: "Fall Arrest Lanyard with Shock Absorber - 2m",
    description_tr: "Yüksekten düşmelere karşı şok emici entegreli çift kollu lanyard.",
    description_en: "Double-legged lanyard with integrated shock absorber for fall protection.",
    technicalCode: "YZN-SAFE-022",
    material: "Polyester Kolon",
    certification: "EN 355",
    price: 980,
    quantity: 150,
    inStock: true,
    specs: { uzunluk: "2m", kanca: "Çift Otomatik", kapasite: "100kg" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 68,
    categoryId: "safety",
    name: "Acil Durum Duşu ve Göz Duşu Kombinasyonu",
    name_tr: "Acil Durum Duşu ve Göz Duşu Kombinasyonu",
    name_en: "Emergency Shower and Eye Wash Combination",
    description_tr: "Kimyasal sıçramalarına karşı acil müdahale için entegre güvenlik istasyonu.",
    description_en: "Integrated safety station for emergency response to chemical splashes.",
    technicalCode: "YZN-SAFE-023",
    material: "Paslanmaz Çelik",
    certification: "ANSI Z358.1",
    price: 12500,
    quantity: 10,
    inStock: true,
    specs: { su_akisi: "76 L/dk", aktivasyon: "Çekme Kolu", montaj: "Zemin" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 69,
    categoryId: "safety",
    name: "Yangın Battaniyesi - 1.2x1.8m Cam Elyaf",
    name_tr: "Yangın Battaniyesi - 1.2x1.8m Cam Elyaf",
    name_en: "Fire Blanket - 1.2x1.8m Fiberglass",
    description_tr: "Küçük yangınları söndürmek ve kişiyi korumak için cam elyaf battaniye.",
    description_en: "Fiberglass blanket for extinguishing small fires and protecting individuals.",
    technicalCode: "YZN-SAFE-024",
    material: "Cam Elyaf",
    certification: "EN 1869",
    price: 380,
    quantity: 500,
    inStock: true,
    specs: { boyut: "1.2x1.8m", sicaklik: "550°C", kılıf: "Duvar Tipi" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 70,
    categoryId: "safety",
    name: "İlk Yardım Çantası - Duvar Tipi Endüstriyel",
    name_tr: "İlk Yardım Çantası - Duvar Tipi Endüstriyel",
    name_en: "First Aid Kit - Wall Mounted Industrial",
    description_tr: "İş yerleri için kapsamlı içerikli, duvara monte edilebilir ilk yardım çantası.",
    description_en: "Wall-mountable first aid kit with comprehensive contents for workplaces.",
    technicalCode: "YZN-SAFE-025",
    material: "ABS Plastik",
    certification: "DIN 13157",
    price: 650,
    quantity: 180,
    inStock: true,
    specs: { boyut: "40x30x15cm", içerik: "50 Parça", montaj: "Duvar" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 71,
    categoryId: "safety",
    name: "Kaymaz İş Ayakkabısı - Beyaz Hijyenik S2",
    name_tr: "Kaymaz İş Ayakkabısı - Beyaz Hijyenik S2",
    name_en: "Non-Slip Work Shoe - White Hygienic S2",
    description_tr: "Gıda ve sağlık sektörleri için kaymaz tabanlı, suya dayanıklı hijyenik ayakkabı.",
    description_en: "Non-slip, water-resistant hygienic shoe for food and healthcare sectors.",
    technicalCode: "YZN-SAFE-026",
    material: "Mikrofiber",
    certification: "EN ISO 20345:2011",
    price: 920,
    quantity: 400,
    inStock: true,
    specs: { beden: "35-48", koruma: "S2", taban: "SRC Kaymaz" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 72,
    categoryId: "safety",
    name: "Endüstriyel Temizleme Mendili - Antibakteriyel",
    name_tr: "Endüstriyel Temizleme Mendili - Antibakteriyel",
    name_en: "Industrial Cleaning Wipe - Antibacterial",
    description_tr: "Yüzeylerdeki bakteri ve virüsleri temizleyen antibakteriyel mendil.",
    description_en: "Antibacterial wipe cleaning bacteria and viruses from surfaces.",
    technicalCode: "YZN-SAFE-027",
    material: "Dokumasız Kumaş",
    certification: "EN 14476",
    price: 120,
    quantity: 1500,
    inStock: true,
    specs: { boyut: "20x30cm", paket: "100 Adet", etki: "%99.9 Bakteri" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 73,
    categoryId: "safety",
    name: "Göz Koruyucu Siperlik - Fileli",
    name_tr: "Göz Koruyucu Siperlik - Fileli",
    name_en: "Mesh Face Shield",
    description_tr: "Ormancılık ve bahçe işleri için darbelere karşı fileli yüz siperliği.",
    description_en: "Mesh face shield against impacts for forestry and gardening.",
    technicalCode: "YZN-SAFE-028",
    material: "Çelik File / ABS",
    certification: "EN 1731",
    price: 320,
    quantity: 250,
    inStock: true,
    specs: { malzeme: "Çelik File", vizör: "Kaldırılabilir", uyum: "Baret" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 74,
    categoryId: "safety",
    name: "Kaynak Dumanı Emme Cihazı - Portatif",
    name_tr: "Kaynak Dumanı Emme Cihazı - Portatif",
    name_en: "Portable Welding Fume Extractor",
    description_tr: "Kaynak dumanlarını çalışma alanından uzaklaştıran taşınabilir filtreleme ünitesi.",
    description_en: "Portable filtering unit removing welding fumes from the work area.",
    technicalCode: "YZN-SAFE-029",
    material: "Çelik / Filtre",
    certification: "EN 15012",
    price: 18000,
    quantity: 8,
    inStock: true,
    specs: { debi: "1000 m³/saat", filtre: "HEPA", guc: "220V" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  },
  {
    id: 75,
    categoryId: "safety",
    name: "Kilitlenebilir İlk Yardım Dolabı - Metal",
    name_tr: "Kilitlenebilir İlk Yardım Dolabı - Metal",
    name_en: "Lockable First Aid Cabinet - Metal",
    description_tr: "İş yerlerinde ilk yardım malzemelerini güvenli ve düzenli tutmak için dolap.",
    description_en: "Cabinet to keep first aid supplies safe and organized in workplaces.",
    technicalCode: "YZN-SAFE-030",
    material: "Çelik Sac",
    certification: "ISO 9001",
    price: 950,
    quantity: 50,
    inStock: true,
    specs: { boyut: "45x35x15cm", kilit: "Anahtarlı", montaj: "Duvar" },
    image: "https://images.unsplash.com/photo-1590402444811-bfee29d1df6a?q=80&w=800&auto=format&fit=crop"
  }
];

